//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.235.
// 
#pragma warning disable 1591

namespace UICDS_Services.ResourceInstanceService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ResourceInstanceServiceSoap11", Namespace="http://uicds.org/ResourceInstanceService")]
    public partial class ResourceInstanceServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetResourceInstanceListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetResourceInstanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateEndpointOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckinOperationCompleted;
        
        private System.Threading.SendOrPostCallback UnregisterOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ResourceInstanceServiceService() {
            this.Url = global::UICDS_Services.Properties.Settings.Default.UICDS_Services_ResourceInstanceService_ResourceInstanceServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckoutCompletedEventHandler CheckoutCompleted;
        
        /// <remarks/>
        public event GetResourceInstanceListCompletedEventHandler GetResourceInstanceListCompleted;
        
        /// <remarks/>
        public event GetResourceInstanceCompletedEventHandler GetResourceInstanceCompleted;
        
        /// <remarks/>
        public event RegisterCompletedEventHandler RegisterCompleted;
        
        /// <remarks/>
        public event UpdateEndpointCompletedEventHandler UpdateEndpointCompleted;
        
        /// <remarks/>
        public event CheckinCompletedEventHandler CheckinCompleted;
        
        /// <remarks/>
        public event UnregisterCompletedEventHandler UnregisterCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CheckoutResponse", Namespace="http://uicds.org/ResourceInstanceService")]
        public CheckoutResponse Checkout([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/ResourceInstanceService")] CheckoutRequest CheckoutRequest) {
            object[] results = this.Invoke("Checkout", new object[] {
                        CheckoutRequest});
            return ((CheckoutResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CheckoutAsync(CheckoutRequest CheckoutRequest) {
            this.CheckoutAsync(CheckoutRequest, null);
        }
        
        /// <remarks/>
        public void CheckoutAsync(CheckoutRequest CheckoutRequest, object userState) {
            if ((this.CheckoutOperationCompleted == null)) {
                this.CheckoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckoutOperationCompleted);
            }
            this.InvokeAsync("Checkout", new object[] {
                        CheckoutRequest}, this.CheckoutOperationCompleted, userState);
        }
        
        private void OnCheckoutOperationCompleted(object arg) {
            if ((this.CheckoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckoutCompleted(this, new CheckoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetResourceInstanceListResponse", Namespace="http://uicds.org/ResourceInstanceService")]
        public GetResourceInstanceListResponse GetResourceInstanceList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/ResourceInstanceService")] GetResourceInstanceListRequest GetResourceInstanceListRequest) {
            object[] results = this.Invoke("GetResourceInstanceList", new object[] {
                        GetResourceInstanceListRequest});
            return ((GetResourceInstanceListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetResourceInstanceListAsync(GetResourceInstanceListRequest GetResourceInstanceListRequest) {
            this.GetResourceInstanceListAsync(GetResourceInstanceListRequest, null);
        }
        
        /// <remarks/>
        public void GetResourceInstanceListAsync(GetResourceInstanceListRequest GetResourceInstanceListRequest, object userState) {
            if ((this.GetResourceInstanceListOperationCompleted == null)) {
                this.GetResourceInstanceListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetResourceInstanceListOperationCompleted);
            }
            this.InvokeAsync("GetResourceInstanceList", new object[] {
                        GetResourceInstanceListRequest}, this.GetResourceInstanceListOperationCompleted, userState);
        }
        
        private void OnGetResourceInstanceListOperationCompleted(object arg) {
            if ((this.GetResourceInstanceListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetResourceInstanceListCompleted(this, new GetResourceInstanceListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetResourceInstanceResponse", Namespace="http://uicds.org/ResourceInstanceService")]
        public GetResourceInstanceResponse GetResourceInstance([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/ResourceInstanceService")] GetResourceInstanceRequest GetResourceInstanceRequest) {
            object[] results = this.Invoke("GetResourceInstance", new object[] {
                        GetResourceInstanceRequest});
            return ((GetResourceInstanceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetResourceInstanceAsync(GetResourceInstanceRequest GetResourceInstanceRequest) {
            this.GetResourceInstanceAsync(GetResourceInstanceRequest, null);
        }
        
        /// <remarks/>
        public void GetResourceInstanceAsync(GetResourceInstanceRequest GetResourceInstanceRequest, object userState) {
            if ((this.GetResourceInstanceOperationCompleted == null)) {
                this.GetResourceInstanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetResourceInstanceOperationCompleted);
            }
            this.InvokeAsync("GetResourceInstance", new object[] {
                        GetResourceInstanceRequest}, this.GetResourceInstanceOperationCompleted, userState);
        }
        
        private void OnGetResourceInstanceOperationCompleted(object arg) {
            if ((this.GetResourceInstanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetResourceInstanceCompleted(this, new GetResourceInstanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RegisterResponse", Namespace="http://uicds.org/ResourceInstanceService")]
        public RegisterResponse Register([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/ResourceInstanceService")] RegisterRequest RegisterRequest) {
            object[] results = this.Invoke("Register", new object[] {
                        RegisterRequest});
            return ((RegisterResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterAsync(RegisterRequest RegisterRequest) {
            this.RegisterAsync(RegisterRequest, null);
        }
        
        /// <remarks/>
        public void RegisterAsync(RegisterRequest RegisterRequest, object userState) {
            if ((this.RegisterOperationCompleted == null)) {
                this.RegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterOperationCompleted);
            }
            this.InvokeAsync("Register", new object[] {
                        RegisterRequest}, this.RegisterOperationCompleted, userState);
        }
        
        private void OnRegisterOperationCompleted(object arg) {
            if ((this.RegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterCompleted(this, new RegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UpdateEndpointResponse", Namespace="http://uicds.org/ResourceInstanceService")]
        public UpdateEndpointResponse UpdateEndpoint([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/ResourceInstanceService")] UpdateEndpointRequest UpdateEndpointRequest) {
            object[] results = this.Invoke("UpdateEndpoint", new object[] {
                        UpdateEndpointRequest});
            return ((UpdateEndpointResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateEndpointAsync(UpdateEndpointRequest UpdateEndpointRequest) {
            this.UpdateEndpointAsync(UpdateEndpointRequest, null);
        }
        
        /// <remarks/>
        public void UpdateEndpointAsync(UpdateEndpointRequest UpdateEndpointRequest, object userState) {
            if ((this.UpdateEndpointOperationCompleted == null)) {
                this.UpdateEndpointOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateEndpointOperationCompleted);
            }
            this.InvokeAsync("UpdateEndpoint", new object[] {
                        UpdateEndpointRequest}, this.UpdateEndpointOperationCompleted, userState);
        }
        
        private void OnUpdateEndpointOperationCompleted(object arg) {
            if ((this.UpdateEndpointCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateEndpointCompleted(this, new UpdateEndpointCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CheckinResponse", Namespace="http://uicds.org/ResourceInstanceService")]
        public CheckinResponse Checkin([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/ResourceInstanceService")] CheckinRequest CheckinRequest) {
            object[] results = this.Invoke("Checkin", new object[] {
                        CheckinRequest});
            return ((CheckinResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CheckinAsync(CheckinRequest CheckinRequest) {
            this.CheckinAsync(CheckinRequest, null);
        }
        
        /// <remarks/>
        public void CheckinAsync(CheckinRequest CheckinRequest, object userState) {
            if ((this.CheckinOperationCompleted == null)) {
                this.CheckinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckinOperationCompleted);
            }
            this.InvokeAsync("Checkin", new object[] {
                        CheckinRequest}, this.CheckinOperationCompleted, userState);
        }
        
        private void OnCheckinOperationCompleted(object arg) {
            if ((this.CheckinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckinCompleted(this, new CheckinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UnregisterResponse", Namespace="http://uicds.org/ResourceInstanceService")]
        public UnregisterResponse Unregister([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/ResourceInstanceService")] UnregisterRequest UnregisterRequest) {
            object[] results = this.Invoke("Unregister", new object[] {
                        UnregisterRequest});
            return ((UnregisterResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UnregisterAsync(UnregisterRequest UnregisterRequest) {
            this.UnregisterAsync(UnregisterRequest, null);
        }
        
        /// <remarks/>
        public void UnregisterAsync(UnregisterRequest UnregisterRequest, object userState) {
            if ((this.UnregisterOperationCompleted == null)) {
                this.UnregisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnregisterOperationCompleted);
            }
            this.InvokeAsync("Unregister", new object[] {
                        UnregisterRequest}, this.UnregisterOperationCompleted, userState);
        }
        
        private void OnUnregisterOperationCompleted(object arg) {
            if ((this.UnregisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnregisterCompleted(this, new UnregisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceInstanceService")]
    public partial class CheckoutRequest {
        
        private ResourceInstance resourceInstanceField;
        
        /// <remarks/>
        public ResourceInstance ResourceInstance {
            get {
                return this.resourceInstanceField;
            }
            set {
                this.resourceInstanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/ResourceInstanceService")]
    public partial class ResourceInstance {
        
        private IdentifierType idField;
        
        private string descriptionField;
        
        private ResourceInstanceSourceIdentification sourceIdentificationField;
        
        private CodespaceValueType[] keywordField;
        
        private EndpointReferenceType[] endpointsField;
        
        private IdentifierType[] profileIDsField;
        
        /// <remarks/>
        public IdentifierType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public ResourceInstanceSourceIdentification SourceIdentification {
            get {
                return this.sourceIdentificationField;
            }
            set {
                this.sourceIdentificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Keyword")]
        public CodespaceValueType[] Keyword {
            get {
                return this.keywordField;
            }
            set {
                this.keywordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Endpoint", IsNullable=false)]
        public EndpointReferenceType[] Endpoints {
            get {
                return this.endpointsField;
            }
            set {
                this.endpointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ProfileID", IsNullable=false)]
        public IdentifierType[] ProfileIDs {
            get {
                return this.profileIDsField;
            }
            set {
                this.profileIDsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.saic.com/precis/2009/06/base")]
    public partial class IdentifierType {
        
        private string labelField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class MetadataType {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class ReferenceParametersType {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class AttributedURIType {
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class EndpointReferenceType {
        
        private AttributedURIType addressField;
        
        private ReferenceParametersType referenceParametersField;
        
        private MetadataType metadataField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public AttributedURIType Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public ReferenceParametersType ReferenceParameters {
            get {
                return this.referenceParametersField;
            }
            set {
                this.referenceParametersField = value;
            }
        }
        
        /// <remarks/>
        public MetadataType Metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.saic.com/precis/2009/06/base")]
    public partial class CodespaceValueType {
        
        private string labelField;
        
        private string codespaceField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string codespace {
            get {
                return this.codespaceField;
            }
            set {
                this.codespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceInstanceService")]
    public partial class ResourceInstanceSourceIdentification {
        
        private IdentifierType localResourceIDField;
        
        private string coreIDField;
        
        /// <remarks/>
        public IdentifierType LocalResourceID {
            get {
                return this.localResourceIDField;
            }
            set {
                this.localResourceIDField = value;
            }
        }
        
        /// <remarks/>
        public string CoreID {
            get {
                return this.coreIDField;
            }
            set {
                this.coreIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceInstanceService")]
    public partial class CheckoutResponse {
        
        private ResourceInstance resourceInstanceField;
        
        /// <remarks/>
        public ResourceInstance ResourceInstance {
            get {
                return this.resourceInstanceField;
            }
            set {
                this.resourceInstanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceInstanceService")]
    public partial class GetResourceInstanceListRequest {
        
        private string queryStringField;
        
        /// <remarks/>
        public string QueryString {
            get {
                return this.queryStringField;
            }
            set {
                this.queryStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceInstanceService")]
    public partial class GetResourceInstanceListResponse {
        
        private ResourceInstance[] resourceInstanceListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ResourceInstance[] ResourceInstanceList {
            get {
                return this.resourceInstanceListField;
            }
            set {
                this.resourceInstanceListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceInstanceService")]
    public partial class GetResourceInstanceRequest {
        
        private IdentifierType idField;
        
        /// <remarks/>
        public IdentifierType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceInstanceService")]
    public partial class GetResourceInstanceResponse {
        
        private ResourceInstance resourceInstanceField;
        
        /// <remarks/>
        public ResourceInstance ResourceInstance {
            get {
                return this.resourceInstanceField;
            }
            set {
                this.resourceInstanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceInstanceService")]
    public partial class RegisterRequest {
        
        private IdentifierType idField;
        
        private IdentifierType localResourceIDField;
        
        private IdentifierType resourceProfileIDField;
        
        /// <remarks/>
        public IdentifierType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public IdentifierType LocalResourceID {
            get {
                return this.localResourceIDField;
            }
            set {
                this.localResourceIDField = value;
            }
        }
        
        /// <remarks/>
        public IdentifierType ResourceProfileID {
            get {
                return this.resourceProfileIDField;
            }
            set {
                this.resourceProfileIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceInstanceService")]
    public partial class RegisterResponse {
        
        private ResourceInstance resourceInstanceField;
        
        /// <remarks/>
        public ResourceInstance ResourceInstance {
            get {
                return this.resourceInstanceField;
            }
            set {
                this.resourceInstanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceInstanceService")]
    public partial class UpdateEndpointRequest {
        
        private IdentifierType idField;
        
        private string endpointField;
        
        private bool isWebServiceField;
        
        /// <remarks/>
        public IdentifierType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string Endpoint {
            get {
                return this.endpointField;
            }
            set {
                this.endpointField = value;
            }
        }
        
        /// <remarks/>
        public bool IsWebService {
            get {
                return this.isWebServiceField;
            }
            set {
                this.isWebServiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceInstanceService")]
    public partial class UpdateEndpointResponse {
        
        private ResourceInstance resourceInstanceField;
        
        /// <remarks/>
        public ResourceInstance ResourceInstance {
            get {
                return this.resourceInstanceField;
            }
            set {
                this.resourceInstanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceInstanceService")]
    public partial class CheckinRequest {
        
        private IdentifierType idField;
        
        private IdentifierType localResourceIDField;
        
        private IdentifierType resourceProfileIDField;
        
        /// <remarks/>
        public IdentifierType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public IdentifierType LocalResourceID {
            get {
                return this.localResourceIDField;
            }
            set {
                this.localResourceIDField = value;
            }
        }
        
        /// <remarks/>
        public IdentifierType ResourceProfileID {
            get {
                return this.resourceProfileIDField;
            }
            set {
                this.resourceProfileIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceInstanceService")]
    public partial class CheckinResponse {
        
        private ResourceInstance resourceInstanceField;
        
        /// <remarks/>
        public ResourceInstance ResourceInstance {
            get {
                return this.resourceInstanceField;
            }
            set {
                this.resourceInstanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceInstanceService")]
    public partial class UnregisterRequest {
        
        private IdentifierType idField;
        
        /// <remarks/>
        public IdentifierType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceInstanceService")]
    public partial class UnregisterResponse {
        
        private IdentifierType idField;
        
        /// <remarks/>
        public IdentifierType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CheckoutCompletedEventHandler(object sender, CheckoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CheckoutResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CheckoutResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetResourceInstanceListCompletedEventHandler(object sender, GetResourceInstanceListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetResourceInstanceListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetResourceInstanceListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetResourceInstanceListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetResourceInstanceListResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetResourceInstanceCompletedEventHandler(object sender, GetResourceInstanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetResourceInstanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetResourceInstanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetResourceInstanceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetResourceInstanceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RegisterCompletedEventHandler(object sender, RegisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RegisterResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RegisterResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateEndpointCompletedEventHandler(object sender, UpdateEndpointCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateEndpointCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateEndpointCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateEndpointResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateEndpointResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CheckinCompletedEventHandler(object sender, CheckinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CheckinResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CheckinResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UnregisterCompletedEventHandler(object sender, UnregisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UnregisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UnregisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UnregisterResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UnregisterResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591