//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3082.
// 
#pragma warning disable 1591

namespace TestJavaWS.DirectoryWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DirectoryServiceSoap11", Namespace="http://uicds.org/DirectoryService")]
    public partial class DirectoryServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RegisterExternalToolOperationCompleted;
        
        private System.Threading.SendOrPostCallback UnregisterUICDSServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback UnregisterExternalToolOperationCompleted;
        
        private System.Threading.SendOrPostCallback UnregisterExternalDataSourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIncidentListOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterUICDSServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSOSListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetExternalToolListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCoreListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServiceListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetExternalDataSourceListOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterExternalDataSourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterSOSOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserListOperationCompleted;
        
        private System.Threading.SendOrPostCallback UnregisterSOSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DirectoryServiceService() {
            this.Url = global::TestJavaWS.Properties.Settings.Default.TestJavaWS_DirectoryWS_DirectoryServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RegisterExternalToolCompletedEventHandler RegisterExternalToolCompleted;
        
        /// <remarks/>
        public event UnregisterUICDSServiceCompletedEventHandler UnregisterUICDSServiceCompleted;
        
        /// <remarks/>
        public event UnregisterExternalToolCompletedEventHandler UnregisterExternalToolCompleted;
        
        /// <remarks/>
        public event UnregisterExternalDataSourceCompletedEventHandler UnregisterExternalDataSourceCompleted;
        
        /// <remarks/>
        public event GetIncidentListCompletedEventHandler GetIncidentListCompleted;
        
        /// <remarks/>
        public event RegisterUICDSServiceCompletedEventHandler RegisterUICDSServiceCompleted;
        
        /// <remarks/>
        public event GetSOSListCompletedEventHandler GetSOSListCompleted;
        
        /// <remarks/>
        public event GetExternalToolListCompletedEventHandler GetExternalToolListCompleted;
        
        /// <remarks/>
        public event GetCoreListCompletedEventHandler GetCoreListCompleted;
        
        /// <remarks/>
        public event GetServiceListCompletedEventHandler GetServiceListCompleted;
        
        /// <remarks/>
        public event GetExternalDataSourceListCompletedEventHandler GetExternalDataSourceListCompleted;
        
        /// <remarks/>
        public event RegisterExternalDataSourceCompletedEventHandler RegisterExternalDataSourceCompleted;
        
        /// <remarks/>
        public event RegisterSOSCompletedEventHandler RegisterSOSCompleted;
        
        /// <remarks/>
        public event GetUserListCompletedEventHandler GetUserListCompleted;
        
        /// <remarks/>
        public event UnregisterSOSCompletedEventHandler UnregisterSOSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void RegisterExternalTool([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/DirectoryService")] RegisterExternalToolRequestType RegisterExternalToolRequest) {
            this.Invoke("RegisterExternalTool", new object[] {
                        RegisterExternalToolRequest});
        }
        
        /// <remarks/>
        public void RegisterExternalToolAsync(RegisterExternalToolRequestType RegisterExternalToolRequest) {
            this.RegisterExternalToolAsync(RegisterExternalToolRequest, null);
        }
        
        /// <remarks/>
        public void RegisterExternalToolAsync(RegisterExternalToolRequestType RegisterExternalToolRequest, object userState) {
            if ((this.RegisterExternalToolOperationCompleted == null)) {
                this.RegisterExternalToolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterExternalToolOperationCompleted);
            }
            this.InvokeAsync("RegisterExternalTool", new object[] {
                        RegisterExternalToolRequest}, this.RegisterExternalToolOperationCompleted, userState);
        }
        
        private void OnRegisterExternalToolOperationCompleted(object arg) {
            if ((this.RegisterExternalToolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterExternalToolCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void UnregisterUICDSService([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/DirectoryService")] UnregisterUICDSServiceRequestType UnregisterUICDSServiceRequest) {
            this.Invoke("UnregisterUICDSService", new object[] {
                        UnregisterUICDSServiceRequest});
        }
        
        /// <remarks/>
        public void UnregisterUICDSServiceAsync(UnregisterUICDSServiceRequestType UnregisterUICDSServiceRequest) {
            this.UnregisterUICDSServiceAsync(UnregisterUICDSServiceRequest, null);
        }
        
        /// <remarks/>
        public void UnregisterUICDSServiceAsync(UnregisterUICDSServiceRequestType UnregisterUICDSServiceRequest, object userState) {
            if ((this.UnregisterUICDSServiceOperationCompleted == null)) {
                this.UnregisterUICDSServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnregisterUICDSServiceOperationCompleted);
            }
            this.InvokeAsync("UnregisterUICDSService", new object[] {
                        UnregisterUICDSServiceRequest}, this.UnregisterUICDSServiceOperationCompleted, userState);
        }
        
        private void OnUnregisterUICDSServiceOperationCompleted(object arg) {
            if ((this.UnregisterUICDSServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnregisterUICDSServiceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void UnregisterExternalTool([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/DirectoryService")] UnregisterExternalToolRequestType UnregisterExternalToolRequest) {
            this.Invoke("UnregisterExternalTool", new object[] {
                        UnregisterExternalToolRequest});
        }
        
        /// <remarks/>
        public void UnregisterExternalToolAsync(UnregisterExternalToolRequestType UnregisterExternalToolRequest) {
            this.UnregisterExternalToolAsync(UnregisterExternalToolRequest, null);
        }
        
        /// <remarks/>
        public void UnregisterExternalToolAsync(UnregisterExternalToolRequestType UnregisterExternalToolRequest, object userState) {
            if ((this.UnregisterExternalToolOperationCompleted == null)) {
                this.UnregisterExternalToolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnregisterExternalToolOperationCompleted);
            }
            this.InvokeAsync("UnregisterExternalTool", new object[] {
                        UnregisterExternalToolRequest}, this.UnregisterExternalToolOperationCompleted, userState);
        }
        
        private void OnUnregisterExternalToolOperationCompleted(object arg) {
            if ((this.UnregisterExternalToolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnregisterExternalToolCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void UnregisterExternalDataSource([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/DirectoryService")] UnregisterExternalDataSourceRequestType UnregisterExternalDataSourceRequest) {
            this.Invoke("UnregisterExternalDataSource", new object[] {
                        UnregisterExternalDataSourceRequest});
        }
        
        /// <remarks/>
        public void UnregisterExternalDataSourceAsync(UnregisterExternalDataSourceRequestType UnregisterExternalDataSourceRequest) {
            this.UnregisterExternalDataSourceAsync(UnregisterExternalDataSourceRequest, null);
        }
        
        /// <remarks/>
        public void UnregisterExternalDataSourceAsync(UnregisterExternalDataSourceRequestType UnregisterExternalDataSourceRequest, object userState) {
            if ((this.UnregisterExternalDataSourceOperationCompleted == null)) {
                this.UnregisterExternalDataSourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnregisterExternalDataSourceOperationCompleted);
            }
            this.InvokeAsync("UnregisterExternalDataSource", new object[] {
                        UnregisterExternalDataSourceRequest}, this.UnregisterExternalDataSourceOperationCompleted, userState);
        }
        
        private void OnUnregisterExternalDataSourceOperationCompleted(object arg) {
            if ((this.UnregisterExternalDataSourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnregisterExternalDataSourceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetIncidentListResponse", Namespace="http://uicds.org/DirectoryService")]
        public GetIncidentListResponseType GetIncidentList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/DirectoryService")] GetIncidentListRequestType GetIncidentListRequest) {
            object[] results = this.Invoke("GetIncidentList", new object[] {
                        GetIncidentListRequest});
            return ((GetIncidentListResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetIncidentListAsync(GetIncidentListRequestType GetIncidentListRequest) {
            this.GetIncidentListAsync(GetIncidentListRequest, null);
        }
        
        /// <remarks/>
        public void GetIncidentListAsync(GetIncidentListRequestType GetIncidentListRequest, object userState) {
            if ((this.GetIncidentListOperationCompleted == null)) {
                this.GetIncidentListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIncidentListOperationCompleted);
            }
            this.InvokeAsync("GetIncidentList", new object[] {
                        GetIncidentListRequest}, this.GetIncidentListOperationCompleted, userState);
        }
        
        private void OnGetIncidentListOperationCompleted(object arg) {
            if ((this.GetIncidentListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIncidentListCompleted(this, new GetIncidentListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void RegisterUICDSService([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/DirectoryService")] RegisterUICDSServiceRequestType RegisterUICDSServiceRequest) {
            this.Invoke("RegisterUICDSService", new object[] {
                        RegisterUICDSServiceRequest});
        }
        
        /// <remarks/>
        public void RegisterUICDSServiceAsync(RegisterUICDSServiceRequestType RegisterUICDSServiceRequest) {
            this.RegisterUICDSServiceAsync(RegisterUICDSServiceRequest, null);
        }
        
        /// <remarks/>
        public void RegisterUICDSServiceAsync(RegisterUICDSServiceRequestType RegisterUICDSServiceRequest, object userState) {
            if ((this.RegisterUICDSServiceOperationCompleted == null)) {
                this.RegisterUICDSServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterUICDSServiceOperationCompleted);
            }
            this.InvokeAsync("RegisterUICDSService", new object[] {
                        RegisterUICDSServiceRequest}, this.RegisterUICDSServiceOperationCompleted, userState);
        }
        
        private void OnRegisterUICDSServiceOperationCompleted(object arg) {
            if ((this.RegisterUICDSServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterUICDSServiceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetSOSListResponse", Namespace="http://uicds.org/DirectoryService")]
        public GetSOSListResponseType GetSOSList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/DirectoryService")] GetSOSListRequestType GetSOSListRequest) {
            object[] results = this.Invoke("GetSOSList", new object[] {
                        GetSOSListRequest});
            return ((GetSOSListResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetSOSListAsync(GetSOSListRequestType GetSOSListRequest) {
            this.GetSOSListAsync(GetSOSListRequest, null);
        }
        
        /// <remarks/>
        public void GetSOSListAsync(GetSOSListRequestType GetSOSListRequest, object userState) {
            if ((this.GetSOSListOperationCompleted == null)) {
                this.GetSOSListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSOSListOperationCompleted);
            }
            this.InvokeAsync("GetSOSList", new object[] {
                        GetSOSListRequest}, this.GetSOSListOperationCompleted, userState);
        }
        
        private void OnGetSOSListOperationCompleted(object arg) {
            if ((this.GetSOSListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSOSListCompleted(this, new GetSOSListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetExternalToolListResponse", Namespace="http://uicds.org/DirectoryService")]
        public GetExternalToolListResponseType GetExternalToolList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/DirectoryService")] GetExternalToolListRequestType GetExternalToolListRequest) {
            object[] results = this.Invoke("GetExternalToolList", new object[] {
                        GetExternalToolListRequest});
            return ((GetExternalToolListResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetExternalToolListAsync(GetExternalToolListRequestType GetExternalToolListRequest) {
            this.GetExternalToolListAsync(GetExternalToolListRequest, null);
        }
        
        /// <remarks/>
        public void GetExternalToolListAsync(GetExternalToolListRequestType GetExternalToolListRequest, object userState) {
            if ((this.GetExternalToolListOperationCompleted == null)) {
                this.GetExternalToolListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetExternalToolListOperationCompleted);
            }
            this.InvokeAsync("GetExternalToolList", new object[] {
                        GetExternalToolListRequest}, this.GetExternalToolListOperationCompleted, userState);
        }
        
        private void OnGetExternalToolListOperationCompleted(object arg) {
            if ((this.GetExternalToolListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetExternalToolListCompleted(this, new GetExternalToolListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetCoreListResponse", Namespace="http://uicds.org/DirectoryService")]
        public GetCoreListResponseType GetCoreList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/DirectoryService")] GetCoreListRequestType GetCoreListRequest) {
            object[] results = this.Invoke("GetCoreList", new object[] {
                        GetCoreListRequest});
            return ((GetCoreListResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetCoreListAsync(GetCoreListRequestType GetCoreListRequest) {
            this.GetCoreListAsync(GetCoreListRequest, null);
        }
        
        /// <remarks/>
        public void GetCoreListAsync(GetCoreListRequestType GetCoreListRequest, object userState) {
            if ((this.GetCoreListOperationCompleted == null)) {
                this.GetCoreListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCoreListOperationCompleted);
            }
            this.InvokeAsync("GetCoreList", new object[] {
                        GetCoreListRequest}, this.GetCoreListOperationCompleted, userState);
        }
        
        private void OnGetCoreListOperationCompleted(object arg) {
            if ((this.GetCoreListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCoreListCompleted(this, new GetCoreListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetServiceListResponse", Namespace="http://uicds.org/DirectoryService")]
        public GettServiceListResponseType GetServiceList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/DirectoryService")] GetServicetListRequestType GetServiceListRequest) {
            object[] results = this.Invoke("GetServiceList", new object[] {
                        GetServiceListRequest});
            return ((GettServiceListResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetServiceListAsync(GetServicetListRequestType GetServiceListRequest) {
            this.GetServiceListAsync(GetServiceListRequest, null);
        }
        
        /// <remarks/>
        public void GetServiceListAsync(GetServicetListRequestType GetServiceListRequest, object userState) {
            if ((this.GetServiceListOperationCompleted == null)) {
                this.GetServiceListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServiceListOperationCompleted);
            }
            this.InvokeAsync("GetServiceList", new object[] {
                        GetServiceListRequest}, this.GetServiceListOperationCompleted, userState);
        }
        
        private void OnGetServiceListOperationCompleted(object arg) {
            if ((this.GetServiceListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServiceListCompleted(this, new GetServiceListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetExternalDataSourceListResponse", Namespace="http://uicds.org/DirectoryService")]
        public GetExternalDataSourceListResponseType GetExternalDataSourceList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/DirectoryService")] GetExternalDataSourceListRequestType GetExternalDataSourceListRequest) {
            object[] results = this.Invoke("GetExternalDataSourceList", new object[] {
                        GetExternalDataSourceListRequest});
            return ((GetExternalDataSourceListResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetExternalDataSourceListAsync(GetExternalDataSourceListRequestType GetExternalDataSourceListRequest) {
            this.GetExternalDataSourceListAsync(GetExternalDataSourceListRequest, null);
        }
        
        /// <remarks/>
        public void GetExternalDataSourceListAsync(GetExternalDataSourceListRequestType GetExternalDataSourceListRequest, object userState) {
            if ((this.GetExternalDataSourceListOperationCompleted == null)) {
                this.GetExternalDataSourceListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetExternalDataSourceListOperationCompleted);
            }
            this.InvokeAsync("GetExternalDataSourceList", new object[] {
                        GetExternalDataSourceListRequest}, this.GetExternalDataSourceListOperationCompleted, userState);
        }
        
        private void OnGetExternalDataSourceListOperationCompleted(object arg) {
            if ((this.GetExternalDataSourceListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetExternalDataSourceListCompleted(this, new GetExternalDataSourceListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void RegisterExternalDataSource([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/DirectoryService")] RegisterExternalDataSourceRequestType RegisterExternalDataSourceRequest) {
            this.Invoke("RegisterExternalDataSource", new object[] {
                        RegisterExternalDataSourceRequest});
        }
        
        /// <remarks/>
        public void RegisterExternalDataSourceAsync(RegisterExternalDataSourceRequestType RegisterExternalDataSourceRequest) {
            this.RegisterExternalDataSourceAsync(RegisterExternalDataSourceRequest, null);
        }
        
        /// <remarks/>
        public void RegisterExternalDataSourceAsync(RegisterExternalDataSourceRequestType RegisterExternalDataSourceRequest, object userState) {
            if ((this.RegisterExternalDataSourceOperationCompleted == null)) {
                this.RegisterExternalDataSourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterExternalDataSourceOperationCompleted);
            }
            this.InvokeAsync("RegisterExternalDataSource", new object[] {
                        RegisterExternalDataSourceRequest}, this.RegisterExternalDataSourceOperationCompleted, userState);
        }
        
        private void OnRegisterExternalDataSourceOperationCompleted(object arg) {
            if ((this.RegisterExternalDataSourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterExternalDataSourceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void RegisterSOS([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/DirectoryService")] RegisterSOSRequestType RegisterSOSRequest) {
            this.Invoke("RegisterSOS", new object[] {
                        RegisterSOSRequest});
        }
        
        /// <remarks/>
        public void RegisterSOSAsync(RegisterSOSRequestType RegisterSOSRequest) {
            this.RegisterSOSAsync(RegisterSOSRequest, null);
        }
        
        /// <remarks/>
        public void RegisterSOSAsync(RegisterSOSRequestType RegisterSOSRequest, object userState) {
            if ((this.RegisterSOSOperationCompleted == null)) {
                this.RegisterSOSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterSOSOperationCompleted);
            }
            this.InvokeAsync("RegisterSOS", new object[] {
                        RegisterSOSRequest}, this.RegisterSOSOperationCompleted, userState);
        }
        
        private void OnRegisterSOSOperationCompleted(object arg) {
            if ((this.RegisterSOSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterSOSCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetUserListResponse", Namespace="http://uicds.org/DirectoryService")]
        public GetUserListResponseType GetUserList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/DirectoryService")] GetUserListRequestType GetUserListRequest) {
            object[] results = this.Invoke("GetUserList", new object[] {
                        GetUserListRequest});
            return ((GetUserListResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserListAsync(GetUserListRequestType GetUserListRequest) {
            this.GetUserListAsync(GetUserListRequest, null);
        }
        
        /// <remarks/>
        public void GetUserListAsync(GetUserListRequestType GetUserListRequest, object userState) {
            if ((this.GetUserListOperationCompleted == null)) {
                this.GetUserListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserListOperationCompleted);
            }
            this.InvokeAsync("GetUserList", new object[] {
                        GetUserListRequest}, this.GetUserListOperationCompleted, userState);
        }
        
        private void OnGetUserListOperationCompleted(object arg) {
            if ((this.GetUserListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserListCompleted(this, new GetUserListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void UnregisterSOS([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/DirectoryService")] UnregisterSOSRequestType UnregisterSOSRequest) {
            this.Invoke("UnregisterSOS", new object[] {
                        UnregisterSOSRequest});
        }
        
        /// <remarks/>
        public void UnregisterSOSAsync(UnregisterSOSRequestType UnregisterSOSRequest) {
            this.UnregisterSOSAsync(UnregisterSOSRequest, null);
        }
        
        /// <remarks/>
        public void UnregisterSOSAsync(UnregisterSOSRequestType UnregisterSOSRequest, object userState) {
            if ((this.UnregisterSOSOperationCompleted == null)) {
                this.UnregisterSOSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnregisterSOSOperationCompleted);
            }
            this.InvokeAsync("UnregisterSOS", new object[] {
                        UnregisterSOSRequest}, this.UnregisterSOSOperationCompleted, userState);
        }
        
        private void OnUnregisterSOSOperationCompleted(object arg) {
            if ((this.UnregisterSOSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnregisterSOSCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class RegisterExternalToolRequestType {
        
        private ExternalToolConfigType externalToolField;
        
        /// <remarks/>
        public ExternalToolConfigType ExternalTool {
            get {
                return this.externalToolField;
            }
            set {
                this.externalToolField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/ExternalToolConfig")]
    public partial class ExternalToolConfigType {
        
        private string uRNField;
        
        private string toolNameField;
        
        private string coreNameField;
        
        private string[] publishedProductsField;
        
        private string[] subscribedProductsField;
        
        /// <remarks/>
        public string URN {
            get {
                return this.uRNField;
            }
            set {
                this.uRNField = value;
            }
        }
        
        /// <remarks/>
        public string toolName {
            get {
                return this.toolNameField;
            }
            set {
                this.toolNameField = value;
            }
        }
        
        /// <remarks/>
        public string coreName {
            get {
                return this.coreNameField;
            }
            set {
                this.coreNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("productType", Namespace="http://uicds.org/DirectoryServiceData", IsNullable=false)]
        public string[] publishedProducts {
            get {
                return this.publishedProductsField;
            }
            set {
                this.publishedProductsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("productType", Namespace="http://uicds.org/DirectoryServiceData", IsNullable=false)]
        public string[] subscribedProducts {
            get {
                return this.subscribedProductsField;
            }
            set {
                this.subscribedProductsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class UnregisterSOSRequestType {
        
        private string sosIDField;
        
        /// <remarks/>
        public string sosID {
            get {
                return this.sosIDField;
            }
            set {
                this.sosIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/UserConfig")]
    public partial class UserConfigType {
        
        private string idField;
        
        private string nameField;
        
        private UserStatusType onlineStatusField;
        
        private string coreNameField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public UserStatusType OnlineStatus {
            get {
                return this.onlineStatusField;
            }
            set {
                this.onlineStatusField = value;
            }
        }
        
        /// <remarks/>
        public string coreName {
            get {
                return this.coreNameField;
            }
            set {
                this.coreNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/UserConfig")]
    public enum UserStatusType {
        
        /// <remarks/>
        Online,
        
        /// <remarks/>
        Offline,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class GetUserListResponseType {
        
        private UserConfigType[] userListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("User", Namespace="http://uicds.org/UserConfig", IsNullable=false)]
        public UserConfigType[] userList {
            get {
                return this.userListField;
            }
            set {
                this.userListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class GetUserListRequestType {
        
        private string coreNameField;
        
        /// <remarks/>
        public string coreName {
            get {
                return this.coreNameField;
            }
            set {
                this.coreNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class RegisterSOSRequestType {
        
        private SOSConfigType sosField;
        
        /// <remarks/>
        public SOSConfigType sos {
            get {
                return this.sosField;
            }
            set {
                this.sosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/SOSConfig")]
    public partial class SOSConfigType {
        
        private string uRNField;
        
        private string serviceIDField;
        
        /// <remarks/>
        public string URN {
            get {
                return this.uRNField;
            }
            set {
                this.uRNField = value;
            }
        }
        
        /// <remarks/>
        public string serviceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class RegisterExternalDataSourceRequestType {
        
        private string uRNField;
        
        /// <remarks/>
        public string URN {
            get {
                return this.uRNField;
            }
            set {
                this.uRNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/ExternalDataSourceConfig")]
    public partial class ExternalDataSourceConfigType {
        
        private string uRNField;
        
        private string coreNameField;
        
        /// <remarks/>
        public string URN {
            get {
                return this.uRNField;
            }
            set {
                this.uRNField = value;
            }
        }
        
        /// <remarks/>
        public string coreName {
            get {
                return this.coreNameField;
            }
            set {
                this.coreNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class GetExternalDataSourceListResponseType {
        
        private ExternalDataSourceConfigType[] externalDataSourceListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ExternalDataSource", Namespace="http://uicds.org/ExternalDataSourceConfig", IsNullable=false)]
        public ExternalDataSourceConfigType[] externalDataSourceList {
            get {
                return this.externalDataSourceListField;
            }
            set {
                this.externalDataSourceListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class GetExternalDataSourceListRequestType {
        
        private string coreNameField;
        
        /// <remarks/>
        public string coreName {
            get {
                return this.coreNameField;
            }
            set {
                this.coreNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class GettServiceListResponseType {
        
        private ServiceConfigType[] serviceListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Service", Namespace="http://uicds.org/ServiceConfig", IsNullable=false)]
        public ServiceConfigType[] serviceList {
            get {
                return this.serviceListField;
            }
            set {
                this.serviceListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/ServiceConfig")]
    public partial class ServiceConfigType {
        
        private string uRNField;
        
        private string serviceNameField;
        
        private string coreNameField;
        
        private string[] publishedProductsField;
        
        private string[] subscribedProductsField;
        
        /// <remarks/>
        public string URN {
            get {
                return this.uRNField;
            }
            set {
                this.uRNField = value;
            }
        }
        
        /// <remarks/>
        public string serviceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
        
        /// <remarks/>
        public string coreName {
            get {
                return this.coreNameField;
            }
            set {
                this.coreNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("productType", Namespace="http://uicds.org/DirectoryServiceData", IsNullable=false)]
        public string[] publishedProducts {
            get {
                return this.publishedProductsField;
            }
            set {
                this.publishedProductsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("productType", Namespace="http://uicds.org/DirectoryServiceData", IsNullable=false)]
        public string[] subscribedProducts {
            get {
                return this.subscribedProductsField;
            }
            set {
                this.subscribedProductsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class GetServicetListRequestType {
        
        private string coreNameField;
        
        /// <remarks/>
        public string coreName {
            get {
                return this.coreNameField;
            }
            set {
                this.coreNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/CoreConfig")]
    public partial class CoreConfigType {
        
        private string nameField;
        
        private string uRLField;
        
        private CoreStatusType onlineStatusField;
        
        private bool localCoreField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        public CoreStatusType OnlineStatus {
            get {
                return this.onlineStatusField;
            }
            set {
                this.onlineStatusField = value;
            }
        }
        
        /// <remarks/>
        public bool localCore {
            get {
                return this.localCoreField;
            }
            set {
                this.localCoreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/CoreConfig")]
    public enum CoreStatusType {
        
        /// <remarks/>
        Online,
        
        /// <remarks/>
        Offline,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class GetCoreListResponseType {
        
        private CoreConfigType[] coreListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Core", Namespace="http://uicds.org/CoreConfig", IsNullable=false)]
        public CoreConfigType[] coreList {
            get {
                return this.coreListField;
            }
            set {
                this.coreListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class GetCoreListRequestType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class GetExternalToolListResponseType {
        
        private ExternalToolConfigType[] externalToolListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ExternalTool", Namespace="http://uicds.org/ExternalToolConfig", IsNullable=false)]
        public ExternalToolConfigType[] externalToolList {
            get {
                return this.externalToolListField;
            }
            set {
                this.externalToolListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class GetExternalToolListRequestType {
        
        private string coreNameField;
        
        /// <remarks/>
        public string coreName {
            get {
                return this.coreNameField;
            }
            set {
                this.coreNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class GetSOSListResponseType {
        
        private SOSConfigType[] sosListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("sos", Namespace="http://uicds.org/SOSConfig", IsNullable=false)]
        public SOSConfigType[] sosList {
            get {
                return this.sosListField;
            }
            set {
                this.sosListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class GetSOSListRequestType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class RegisterUICDSServiceRequestType {
        
        private ServiceConfigType serviceField;
        
        /// <remarks/>
        public ServiceConfigType Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/IncidentManagementService")]
    public partial class IncidentInfoType {
        
        private string idField;
        
        private string workProductIdField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string dateField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private string owningCoreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WorkProductId {
            get {
                return this.workProductIdField;
            }
            set {
                this.workProductIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OwningCore {
            get {
                return this.owningCoreField;
            }
            set {
                this.owningCoreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class GetIncidentListResponseType {
        
        private IncidentInfoType[] incidentInfoListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("incidentInfo", IsNullable=false)]
        public IncidentInfoType[] incidentInfoList {
            get {
                return this.incidentInfoListField;
            }
            set {
                this.incidentInfoListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class GetIncidentListRequestType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class UnregisterExternalDataSourceRequestType {
        
        private string uRNField;
        
        /// <remarks/>
        public string URN {
            get {
                return this.uRNField;
            }
            set {
                this.uRNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class UnregisterExternalToolRequestType {
        
        private string uRNField;
        
        /// <remarks/>
        public string URN {
            get {
                return this.uRNField;
            }
            set {
                this.uRNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/DirectoryService")]
    public partial class UnregisterUICDSServiceRequestType {
        
        private string serviceNameField;
        
        /// <remarks/>
        public string serviceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void RegisterExternalToolCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void UnregisterUICDSServiceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void UnregisterExternalToolCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void UnregisterExternalDataSourceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetIncidentListCompletedEventHandler(object sender, GetIncidentListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIncidentListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIncidentListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetIncidentListResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetIncidentListResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void RegisterUICDSServiceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetSOSListCompletedEventHandler(object sender, GetSOSListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSOSListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSOSListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetSOSListResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetSOSListResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetExternalToolListCompletedEventHandler(object sender, GetExternalToolListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetExternalToolListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetExternalToolListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetExternalToolListResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetExternalToolListResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetCoreListCompletedEventHandler(object sender, GetCoreListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCoreListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCoreListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetCoreListResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetCoreListResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetServiceListCompletedEventHandler(object sender, GetServiceListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServiceListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServiceListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GettServiceListResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GettServiceListResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetExternalDataSourceListCompletedEventHandler(object sender, GetExternalDataSourceListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetExternalDataSourceListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetExternalDataSourceListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetExternalDataSourceListResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetExternalDataSourceListResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void RegisterExternalDataSourceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void RegisterSOSCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetUserListCompletedEventHandler(object sender, GetUserListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetUserListResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetUserListResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void UnregisterSOSCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591