//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.235.
// 
#pragma warning disable 1591

namespace UICDS_Services.ResourceProfileService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ResourceProfileServiceSoap11", Namespace="http://uicds.org/ResourceProfileService")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Interest[]))]
    public partial class ResourceProfileServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddInterestOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProfileListOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveInterestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProfileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ResourceProfileServiceService() {
            this.Url = global::UICDS_Services.Properties.Settings.Default.UICDS_Services_ResourceProfileService_ResourceProfileServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddInterestCompletedEventHandler AddInterestCompleted;
        
        /// <remarks/>
        public event CreateProfileCompletedEventHandler CreateProfileCompleted;
        
        /// <remarks/>
        public event DeleteProfileCompletedEventHandler DeleteProfileCompleted;
        
        /// <remarks/>
        public event GetProfileListCompletedEventHandler GetProfileListCompleted;
        
        /// <remarks/>
        public event RemoveInterestCompletedEventHandler RemoveInterestCompleted;
        
        /// <remarks/>
        public event GetProfileCompletedEventHandler GetProfileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("AddInterestResponse", Namespace="http://uicds.org/ResourceProfileService")]
        public AddInterestResponse AddInterest([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/ResourceProfileService")] AddInterestRequest AddInterestRequest) {
            object[] results = this.Invoke("AddInterest", new object[] {
                        AddInterestRequest});
            return ((AddInterestResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AddInterestAsync(AddInterestRequest AddInterestRequest) {
            this.AddInterestAsync(AddInterestRequest, null);
        }
        
        /// <remarks/>
        public void AddInterestAsync(AddInterestRequest AddInterestRequest, object userState) {
            if ((this.AddInterestOperationCompleted == null)) {
                this.AddInterestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddInterestOperationCompleted);
            }
            this.InvokeAsync("AddInterest", new object[] {
                        AddInterestRequest}, this.AddInterestOperationCompleted, userState);
        }
        
        private void OnAddInterestOperationCompleted(object arg) {
            if ((this.AddInterestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddInterestCompleted(this, new AddInterestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CreateProfileResponse", Namespace="http://uicds.org/ResourceProfileService")]
        public CreateProfileResponse CreateProfile([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/ResourceProfileService")] CreateProfileRequest CreateProfileRequest) {
            object[] results = this.Invoke("CreateProfile", new object[] {
                        CreateProfileRequest});
            return ((CreateProfileResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateProfileAsync(CreateProfileRequest CreateProfileRequest) {
            this.CreateProfileAsync(CreateProfileRequest, null);
        }
        
        /// <remarks/>
        public void CreateProfileAsync(CreateProfileRequest CreateProfileRequest, object userState) {
            if ((this.CreateProfileOperationCompleted == null)) {
                this.CreateProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateProfileOperationCompleted);
            }
            this.InvokeAsync("CreateProfile", new object[] {
                        CreateProfileRequest}, this.CreateProfileOperationCompleted, userState);
        }
        
        private void OnCreateProfileOperationCompleted(object arg) {
            if ((this.CreateProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateProfileCompleted(this, new CreateProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteProfileResponse", Namespace="http://uicds.org/ResourceProfileService")]
        public DeleteProfileResponse DeleteProfile([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/ResourceProfileService")] DeleteProfileRequest DeleteProfileRequest) {
            object[] results = this.Invoke("DeleteProfile", new object[] {
                        DeleteProfileRequest});
            return ((DeleteProfileResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteProfileAsync(DeleteProfileRequest DeleteProfileRequest) {
            this.DeleteProfileAsync(DeleteProfileRequest, null);
        }
        
        /// <remarks/>
        public void DeleteProfileAsync(DeleteProfileRequest DeleteProfileRequest, object userState) {
            if ((this.DeleteProfileOperationCompleted == null)) {
                this.DeleteProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteProfileOperationCompleted);
            }
            this.InvokeAsync("DeleteProfile", new object[] {
                        DeleteProfileRequest}, this.DeleteProfileOperationCompleted, userState);
        }
        
        private void OnDeleteProfileOperationCompleted(object arg) {
            if ((this.DeleteProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteProfileCompleted(this, new DeleteProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetProfileListResponse", Namespace="http://uicds.org/ResourceProfileService")]
        public GetProfileListResponse GetProfileList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/ResourceProfileService")] GetProfileListRequest GetProfileListRequest) {
            object[] results = this.Invoke("GetProfileList", new object[] {
                        GetProfileListRequest});
            return ((GetProfileListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetProfileListAsync(GetProfileListRequest GetProfileListRequest) {
            this.GetProfileListAsync(GetProfileListRequest, null);
        }
        
        /// <remarks/>
        public void GetProfileListAsync(GetProfileListRequest GetProfileListRequest, object userState) {
            if ((this.GetProfileListOperationCompleted == null)) {
                this.GetProfileListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProfileListOperationCompleted);
            }
            this.InvokeAsync("GetProfileList", new object[] {
                        GetProfileListRequest}, this.GetProfileListOperationCompleted, userState);
        }
        
        private void OnGetProfileListOperationCompleted(object arg) {
            if ((this.GetProfileListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProfileListCompleted(this, new GetProfileListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RemoveInterestResponse", Namespace="http://uicds.org/ResourceProfileService")]
        public RemoveInterestResponse RemoveInterest([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/ResourceProfileService")] RemoveInterestRequest RemoveInterestRequest) {
            object[] results = this.Invoke("RemoveInterest", new object[] {
                        RemoveInterestRequest});
            return ((RemoveInterestResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveInterestAsync(RemoveInterestRequest RemoveInterestRequest) {
            this.RemoveInterestAsync(RemoveInterestRequest, null);
        }
        
        /// <remarks/>
        public void RemoveInterestAsync(RemoveInterestRequest RemoveInterestRequest, object userState) {
            if ((this.RemoveInterestOperationCompleted == null)) {
                this.RemoveInterestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveInterestOperationCompleted);
            }
            this.InvokeAsync("RemoveInterest", new object[] {
                        RemoveInterestRequest}, this.RemoveInterestOperationCompleted, userState);
        }
        
        private void OnRemoveInterestOperationCompleted(object arg) {
            if ((this.RemoveInterestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveInterestCompleted(this, new RemoveInterestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetProfileResponse", Namespace="http://uicds.org/ResourceProfileService")]
        public GetProfileResponse GetProfile([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/ResourceProfileService")] GetProfileRequest GetProfileRequest) {
            object[] results = this.Invoke("GetProfile", new object[] {
                        GetProfileRequest});
            return ((GetProfileResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetProfileAsync(GetProfileRequest GetProfileRequest) {
            this.GetProfileAsync(GetProfileRequest, null);
        }
        
        /// <remarks/>
        public void GetProfileAsync(GetProfileRequest GetProfileRequest, object userState) {
            if ((this.GetProfileOperationCompleted == null)) {
                this.GetProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProfileOperationCompleted);
            }
            this.InvokeAsync("GetProfile", new object[] {
                        GetProfileRequest}, this.GetProfileOperationCompleted, userState);
        }
        
        private void OnGetProfileOperationCompleted(object arg) {
            if ((this.GetProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProfileCompleted(this, new GetProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceProfileService")]
    public partial class AddInterestRequest {
        
        private IdentifierType idField;
        
        private Interest interestField;
        
        /// <remarks/>
        public IdentifierType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Interest Interest {
            get {
                return this.interestField;
            }
            set {
                this.interestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.saic.com/precis/2009/06/base")]
    public partial class IdentifierType {
        
        private string labelField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.saic.com/precis/2009/06/base")]
    public partial class CodespaceValueType {
        
        private string labelField;
        
        private string codespaceField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string codespace {
            get {
                return this.codespaceField;
            }
            set {
                this.codespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/ResourceProfileService")]
    public partial class ResourceProfile {
        
        private IdentifierType idField;
        
        private string descriptionField;
        
        private CodespaceValueType[] resourceTypingField;
        
        private Interest[] interestsField;
        
        /// <remarks/>
        public IdentifierType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Type", IsNullable=false)]
        public CodespaceValueType[] ResourceTyping {
            get {
                return this.resourceTypingField;
            }
            set {
                this.resourceTypingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Interest[] Interests {
            get {
                return this.interestsField;
            }
            set {
                this.interestsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/ResourceProfileService")]
    public partial class Interest {
        
        private string topicExpressionField;
        
        private QueryExpressionType messageContentField;
        
        private NamespaceMapItemType[] namespaceMapField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string TopicExpression {
            get {
                return this.topicExpressionField;
            }
            set {
                this.topicExpressionField = value;
            }
        }
        
        /// <remarks/>
        public QueryExpressionType MessageContent {
            get {
                return this.messageContentField;
            }
            set {
                this.messageContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Namespace="http://www.saic.com/precis/2009/06/base", IsNullable=false)]
        public NamespaceMapItemType[] NamespaceMap {
            get {
                return this.namespaceMapField;
            }
            set {
                this.namespaceMapField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class QueryExpressionType {
        
        private System.Xml.XmlNode[] anyField;
        
        private string dialectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Dialect {
            get {
                return this.dialectField;
            }
            set {
                this.dialectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.saic.com/precis/2009/06/base")]
    public partial class NamespaceMapItemType {
        
        private string prefixField;
        
        private string uRIField;
        
        /// <remarks/>
        public string Prefix {
            get {
                return this.prefixField;
            }
            set {
                this.prefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceProfileService")]
    public partial class AddInterestResponse {
        
        private ResourceProfile profileField;
        
        /// <remarks/>
        public ResourceProfile Profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceProfileService")]
    public partial class CreateProfileRequest {
        
        private ResourceProfile profileField;
        
        /// <remarks/>
        public ResourceProfile Profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceProfileService")]
    public partial class CreateProfileResponse {
        
        private ResourceProfile profileField;
        
        /// <remarks/>
        public ResourceProfile Profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceProfileService")]
    public partial class DeleteProfileRequest {
        
        private IdentifierType idField;
        
        /// <remarks/>
        public IdentifierType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceProfileService")]
    public partial class DeleteProfileResponse {
        
        private IdentifierType idField;
        
        /// <remarks/>
        public IdentifierType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceProfileService")]
    public partial class GetProfileListRequest {
        
        private string queryStringField;
        
        /// <remarks/>
        public string QueryString {
            get {
                return this.queryStringField;
            }
            set {
                this.queryStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceProfileService")]
    public partial class GetProfileListResponse {
        
        private ResourceProfile[] profileListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ResourceProfile[] ProfileList {
            get {
                return this.profileListField;
            }
            set {
                this.profileListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceProfileService")]
    public partial class RemoveInterestRequest {
        
        private IdentifierType idField;
        
        private Interest interestField;
        
        /// <remarks/>
        public IdentifierType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Interest Interest {
            get {
                return this.interestField;
            }
            set {
                this.interestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceProfileService")]
    public partial class RemoveInterestResponse {
        
        private ResourceProfile profileField;
        
        /// <remarks/>
        public ResourceProfile Profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceProfileService")]
    public partial class GetProfileRequest {
        
        private IdentifierType idField;
        
        /// <remarks/>
        public IdentifierType ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/ResourceProfileService")]
    public partial class GetProfileResponse {
        
        private ResourceProfile profileField;
        
        /// <remarks/>
        public ResourceProfile Profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddInterestCompletedEventHandler(object sender, AddInterestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddInterestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddInterestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddInterestResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddInterestResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateProfileCompletedEventHandler(object sender, CreateProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateProfileResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateProfileResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteProfileCompletedEventHandler(object sender, DeleteProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteProfileResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteProfileResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetProfileListCompletedEventHandler(object sender, GetProfileListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProfileListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProfileListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetProfileListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetProfileListResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RemoveInterestCompletedEventHandler(object sender, RemoveInterestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveInterestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveInterestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RemoveInterestResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RemoveInterestResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetProfileCompletedEventHandler(object sender, GetProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetProfileResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetProfileResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591