//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.235.
// 
#pragma warning disable 1591

namespace UICDS_Services.AgreementService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AgreementServiceSoap11", Namespace="http://uicds.org/AgreementService")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractRingType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractGMLType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeValueType))]
    public partial class AgreementServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateAgreementOperationCompleted;
        
        private System.Threading.SendOrPostCallback RescindAgreementOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateAgreementOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAgreementListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAgreementOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AgreementServiceService() {
            this.Url = global::UICDS_Services.Properties.Settings.Default.UICDS_Services_AgreementService_AgreementServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateAgreementCompletedEventHandler CreateAgreementCompleted;
        
        /// <remarks/>
        public event RescindAgreementCompletedEventHandler RescindAgreementCompleted;
        
        /// <remarks/>
        public event UpdateAgreementCompletedEventHandler UpdateAgreementCompleted;
        
        /// <remarks/>
        public event GetAgreementListCompletedEventHandler GetAgreementListCompleted;
        
        /// <remarks/>
        public event GetAgreementCompletedEventHandler GetAgreementCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CreateAgreementResponse", Namespace="http://uicds.org/AgreementService")]
        public CreateAgreementResponse CreateAgreement([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/AgreementService")] CreateAgreementRequest CreateAgreementRequest) {
            object[] results = this.Invoke("CreateAgreement", new object[] {
                        CreateAgreementRequest});
            return ((CreateAgreementResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAgreementAsync(CreateAgreementRequest CreateAgreementRequest) {
            this.CreateAgreementAsync(CreateAgreementRequest, null);
        }
        
        /// <remarks/>
        public void CreateAgreementAsync(CreateAgreementRequest CreateAgreementRequest, object userState) {
            if ((this.CreateAgreementOperationCompleted == null)) {
                this.CreateAgreementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateAgreementOperationCompleted);
            }
            this.InvokeAsync("CreateAgreement", new object[] {
                        CreateAgreementRequest}, this.CreateAgreementOperationCompleted, userState);
        }
        
        private void OnCreateAgreementOperationCompleted(object arg) {
            if ((this.CreateAgreementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateAgreementCompleted(this, new CreateAgreementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RescindAgreementResponse", Namespace="http://uicds.org/AgreementService")]
        public RescindAgreementResponse RescindAgreement([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/AgreementService")] RescindAgreementRequest RescindAgreementRequest) {
            object[] results = this.Invoke("RescindAgreement", new object[] {
                        RescindAgreementRequest});
            return ((RescindAgreementResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RescindAgreementAsync(RescindAgreementRequest RescindAgreementRequest) {
            this.RescindAgreementAsync(RescindAgreementRequest, null);
        }
        
        /// <remarks/>
        public void RescindAgreementAsync(RescindAgreementRequest RescindAgreementRequest, object userState) {
            if ((this.RescindAgreementOperationCompleted == null)) {
                this.RescindAgreementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRescindAgreementOperationCompleted);
            }
            this.InvokeAsync("RescindAgreement", new object[] {
                        RescindAgreementRequest}, this.RescindAgreementOperationCompleted, userState);
        }
        
        private void OnRescindAgreementOperationCompleted(object arg) {
            if ((this.RescindAgreementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RescindAgreementCompleted(this, new RescindAgreementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UpdateAgreementResponse", Namespace="http://uicds.org/AgreementService")]
        public UpdateAgreementResponse UpdateAgreement([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/AgreementService")] UpdateAgreementRequest UpdateAgreementRequest) {
            object[] results = this.Invoke("UpdateAgreement", new object[] {
                        UpdateAgreementRequest});
            return ((UpdateAgreementResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAgreementAsync(UpdateAgreementRequest UpdateAgreementRequest) {
            this.UpdateAgreementAsync(UpdateAgreementRequest, null);
        }
        
        /// <remarks/>
        public void UpdateAgreementAsync(UpdateAgreementRequest UpdateAgreementRequest, object userState) {
            if ((this.UpdateAgreementOperationCompleted == null)) {
                this.UpdateAgreementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateAgreementOperationCompleted);
            }
            this.InvokeAsync("UpdateAgreement", new object[] {
                        UpdateAgreementRequest}, this.UpdateAgreementOperationCompleted, userState);
        }
        
        private void OnUpdateAgreementOperationCompleted(object arg) {
            if ((this.UpdateAgreementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateAgreementCompleted(this, new UpdateAgreementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetAgreementListResponse", Namespace="http://uicds.org/AgreementService")]
        public GetAgreementListResponse GetAgreementList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/AgreementService")] GetAgreementListRequest GetAgreementListRequest) {
            object[] results = this.Invoke("GetAgreementList", new object[] {
                        GetAgreementListRequest});
            return ((GetAgreementListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAgreementListAsync(GetAgreementListRequest GetAgreementListRequest) {
            this.GetAgreementListAsync(GetAgreementListRequest, null);
        }
        
        /// <remarks/>
        public void GetAgreementListAsync(GetAgreementListRequest GetAgreementListRequest, object userState) {
            if ((this.GetAgreementListOperationCompleted == null)) {
                this.GetAgreementListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAgreementListOperationCompleted);
            }
            this.InvokeAsync("GetAgreementList", new object[] {
                        GetAgreementListRequest}, this.GetAgreementListOperationCompleted, userState);
        }
        
        private void OnGetAgreementListOperationCompleted(object arg) {
            if ((this.GetAgreementListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAgreementListCompleted(this, new GetAgreementListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetAgreementResponse", Namespace="http://uicds.org/AgreementService")]
        public GetAgreementResponse GetAgreement([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/AgreementService")] GetAgreementRequest GetAgreementRequest) {
            object[] results = this.Invoke("GetAgreement", new object[] {
                        GetAgreementRequest});
            return ((GetAgreementResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAgreementAsync(GetAgreementRequest GetAgreementRequest) {
            this.GetAgreementAsync(GetAgreementRequest, null);
        }
        
        /// <remarks/>
        public void GetAgreementAsync(GetAgreementRequest GetAgreementRequest, object userState) {
            if ((this.GetAgreementOperationCompleted == null)) {
                this.GetAgreementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAgreementOperationCompleted);
            }
            this.InvokeAsync("GetAgreement", new object[] {
                        GetAgreementRequest}, this.GetAgreementOperationCompleted, userState);
        }
        
        private void OnGetAgreementOperationCompleted(object arg) {
            if ((this.GetAgreementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAgreementCompleted(this, new GetAgreementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class CreateAgreementRequest {
        
        private AgreementType agreementField;
        
        /// <remarks/>
        public AgreementType Agreement {
            get {
                return this.agreementField;
            }
            set {
                this.agreementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/AgreementService")]
    public partial class AgreementType {
        
        private AgreementTypePrincipals principalsField;
        
        private AgreementTypeShareRules shareRulesField;
        
        /// <remarks/>
        public AgreementTypePrincipals Principals {
            get {
                return this.principalsField;
            }
            set {
                this.principalsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AgreementTypeShareRules ShareRules {
            get {
                return this.shareRulesField;
            }
            set {
                this.shareRulesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class AgreementTypePrincipals {
        
        private IdentifierType localCoreField;
        
        private IdentifierType remoteCoreField;
        
        /// <remarks/>
        public IdentifierType LocalCore {
            get {
                return this.localCoreField;
            }
            set {
                this.localCoreField = value;
            }
        }
        
        /// <remarks/>
        public IdentifierType RemoteCore {
            get {
                return this.remoteCoreField;
            }
            set {
                this.remoteCoreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.saic.com/precis/2009/06/base")]
    public partial class IdentifierType {
        
        private string labelField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public partial class DirectPositionType {
        
        private string srsNameField;
        
        private string srsDimensionField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string srsName {
            get {
                return this.srsNameField;
            }
            set {
                this.srsNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string srsDimension {
            get {
                return this.srsDimensionField;
            }
            set {
                this.srsDimensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LinearRingType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public abstract partial class AbstractRingType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public partial class LinearRingType : AbstractRingType {
        
        private DirectPositionType[] posField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pos")]
        public DirectPositionType[] pos {
            get {
                return this.posField;
            }
            set {
                this.posField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public partial class AbstractRingPropertyType {
        
        private LinearRingType itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LinearRing")]
        public LinearRingType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractGeometryType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractGeometricPrimitiveType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractCurveType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineStringType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PointType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractSurfaceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public abstract partial class AbstractGMLType {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractGeometricPrimitiveType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractCurveType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineStringType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PointType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractSurfaceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public abstract partial class AbstractGeometryType : AbstractGMLType {
        
        private string srsNameField;
        
        private string srsDimensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string srsName {
            get {
                return this.srsNameField;
            }
            set {
                this.srsNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string srsDimension {
            get {
                return this.srsDimensionField;
            }
            set {
                this.srsDimensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractCurveType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineStringType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PointType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AbstractSurfaceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public abstract partial class AbstractGeometricPrimitiveType : AbstractGeometryType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineStringType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public abstract partial class AbstractCurveType : AbstractGeometricPrimitiveType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public partial class LineStringType : AbstractCurveType {
        
        private DirectPositionType[] posField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pos")]
        public DirectPositionType[] pos {
            get {
                return this.posField;
            }
            set {
                this.posField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public partial class PointType : AbstractGeometricPrimitiveType {
        
        private DirectPositionType posField;
        
        /// <remarks/>
        public DirectPositionType pos {
            get {
                return this.posField;
            }
            set {
                this.posField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/gml/3.2")]
    public abstract partial class AbstractSurfaceType : AbstractGeometricPrimitiveType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="PolygonType", Namespace="http://www.opengis.net/gml/3.2")]
    public partial class PolygonType1 : AbstractSurfaceType {
        
        private AbstractRingPropertyType exteriorField;
        
        /// <remarks/>
        public AbstractRingPropertyType exterior {
            get {
                return this.exteriorField;
            }
            set {
                this.exteriorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucore.gov/ucore/2.0")]
    public partial class PolygonType {
        
        private PolygonType1 polygonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.opengis.net/gml/3.2")]
        public PolygonType1 Polygon {
            get {
                return this.polygonField;
            }
            set {
                this.polygonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeInstantType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucore.gov/ucore/2.0")]
    public partial class TimeValueType {
        
        private string valueField;
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucore.gov/ucore/2.0")]
    public partial class TimeInstantType : TimeValueType {
        
        private string uncertaintyIntervalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration")]
        public string UncertaintyInterval {
            get {
                return this.uncertaintyIntervalField;
            }
            set {
                this.uncertaintyIntervalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ucore.gov/ucore/2.0")]
    public partial class TimeIntervalType {
        
        private TimeInstantType startTimeField;
        
        private TimeInstantType endTimeField;
        
        /// <remarks/>
        public TimeInstantType StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        public TimeInstantType EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.saic.com/precis/2009/06/base")]
    public partial class CodespaceValueType {
        
        private string labelField;
        
        private string codespaceField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string codespace {
            get {
                return this.codespaceField;
            }
            set {
                this.codespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/AgreementService")]
    public partial class ConditionType {
        
        private CodespaceValueType interestGroupField;
        
        private TimeIntervalType timeIntervalField;
        
        private PolygonType polygonField;
        
        /// <remarks/>
        public CodespaceValueType InterestGroup {
            get {
                return this.interestGroupField;
            }
            set {
                this.interestGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ucore.gov/ucore/2.0")]
        public TimeIntervalType TimeInterval {
            get {
                return this.timeIntervalField;
            }
            set {
                this.timeIntervalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://ucore.gov/ucore/2.0")]
        public PolygonType Polygon {
            get {
                return this.polygonField;
            }
            set {
                this.polygonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class AgreementTypeShareRules {
        
        private AgreementTypeShareRulesShareRule[] shareRuleField;
        
        private bool enabledField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShareRule")]
        public AgreementTypeShareRulesShareRule[] ShareRule {
            get {
                return this.shareRuleField;
            }
            set {
                this.shareRuleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class AgreementTypeShareRulesShareRule {
        
        private ConditionType conditionField;
        
        private CodespaceValueType[] workProductsField;
        
        private string idField;
        
        private bool enabledField;
        
        /// <remarks/>
        public ConditionType Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Type", Namespace="http://www.saic.com/precis/2009/06/base", IsNullable=false)]
        public CodespaceValueType[] WorkProducts {
            get {
                return this.workProductsField;
            }
            set {
                this.workProductsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class CreateAgreementResponse {
        
        private AgreementType agreementField;
        
        /// <remarks/>
        public AgreementType Agreement {
            get {
                return this.agreementField;
            }
            set {
                this.agreementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class RescindAgreementRequest {
        
        private string coreIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string CoreID {
            get {
                return this.coreIDField;
            }
            set {
                this.coreIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class RescindAgreementResponse {
        
        private string coreIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string CoreID {
            get {
                return this.coreIDField;
            }
            set {
                this.coreIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class UpdateAgreementRequest {
        
        private AgreementType agreementField;
        
        /// <remarks/>
        public AgreementType Agreement {
            get {
                return this.agreementField;
            }
            set {
                this.agreementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class UpdateAgreementResponse {
        
        private AgreementType agreementField;
        
        /// <remarks/>
        public AgreementType Agreement {
            get {
                return this.agreementField;
            }
            set {
                this.agreementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class GetAgreementListRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class GetAgreementListResponse {
        
        private AgreementType[] agreementListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Agreement", IsNullable=false)]
        public AgreementType[] AgreementList {
            get {
                return this.agreementListField;
            }
            set {
                this.agreementListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class GetAgreementRequest {
        
        private string coreIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string CoreID {
            get {
                return this.coreIDField;
            }
            set {
                this.coreIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class GetAgreementResponse {
        
        private AgreementType agreementField;
        
        /// <remarks/>
        public AgreementType Agreement {
            get {
                return this.agreementField;
            }
            set {
                this.agreementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateAgreementCompletedEventHandler(object sender, CreateAgreementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateAgreementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateAgreementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateAgreementResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateAgreementResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RescindAgreementCompletedEventHandler(object sender, RescindAgreementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RescindAgreementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RescindAgreementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RescindAgreementResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RescindAgreementResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateAgreementCompletedEventHandler(object sender, UpdateAgreementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateAgreementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateAgreementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateAgreementResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateAgreementResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAgreementListCompletedEventHandler(object sender, GetAgreementListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAgreementListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAgreementListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAgreementListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAgreementListResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAgreementCompletedEventHandler(object sender, GetAgreementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAgreementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAgreementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAgreementResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAgreementResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591