//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3082.
// 
#pragma warning disable 1591

namespace TestJavaWS.AgreementWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AgreementServiceSoap11", Namespace="http://uicds.org/AgreementService")]
    public partial class AgreementServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateAgreementOperationCompleted;
        
        private System.Threading.SendOrPostCallback RescindAgreementOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAgreementsListOperationCompleted;
        
        private System.Threading.SendOrPostCallback AmendAgreementOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAgreementOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AgreementServiceService() {
            this.Url = global::TestJavaWS.Properties.Settings.Default.TestJavaWS_AgreementWS_AgreementServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateAgreementCompletedEventHandler CreateAgreementCompleted;
        
        /// <remarks/>
        public event RescindAgreementCompletedEventHandler RescindAgreementCompleted;
        
        /// <remarks/>
        public event GetAgreementsListCompletedEventHandler GetAgreementsListCompleted;
        
        /// <remarks/>
        public event AmendAgreementCompletedEventHandler AmendAgreementCompleted;
        
        /// <remarks/>
        public event GetAgreementCompletedEventHandler GetAgreementCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CreateAgreementResponse", Namespace="http://uicds.org/AgreementService")]
        public CreateAgreementResponse CreateAgreement([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/AgreementService")] CreateAgreementRequest CreateAgreementRequest) {
            object[] results = this.Invoke("CreateAgreement", new object[] {
                        CreateAgreementRequest});
            return ((CreateAgreementResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAgreementAsync(CreateAgreementRequest CreateAgreementRequest) {
            this.CreateAgreementAsync(CreateAgreementRequest, null);
        }
        
        /// <remarks/>
        public void CreateAgreementAsync(CreateAgreementRequest CreateAgreementRequest, object userState) {
            if ((this.CreateAgreementOperationCompleted == null)) {
                this.CreateAgreementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateAgreementOperationCompleted);
            }
            this.InvokeAsync("CreateAgreement", new object[] {
                        CreateAgreementRequest}, this.CreateAgreementOperationCompleted, userState);
        }
        
        private void OnCreateAgreementOperationCompleted(object arg) {
            if ((this.CreateAgreementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateAgreementCompleted(this, new CreateAgreementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RescindAgreementResponse", Namespace="http://uicds.org/AgreementService")]
        public RescindAgreementResponse RescindAgreement([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/AgreementService")] RescindAgreementRequest RescindAgreementRequest) {
            object[] results = this.Invoke("RescindAgreement", new object[] {
                        RescindAgreementRequest});
            return ((RescindAgreementResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RescindAgreementAsync(RescindAgreementRequest RescindAgreementRequest) {
            this.RescindAgreementAsync(RescindAgreementRequest, null);
        }
        
        /// <remarks/>
        public void RescindAgreementAsync(RescindAgreementRequest RescindAgreementRequest, object userState) {
            if ((this.RescindAgreementOperationCompleted == null)) {
                this.RescindAgreementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRescindAgreementOperationCompleted);
            }
            this.InvokeAsync("RescindAgreement", new object[] {
                        RescindAgreementRequest}, this.RescindAgreementOperationCompleted, userState);
        }
        
        private void OnRescindAgreementOperationCompleted(object arg) {
            if ((this.RescindAgreementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RescindAgreementCompleted(this, new RescindAgreementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetAgreementsListResponse", Namespace="http://uicds.org/AgreementService")]
        public GetAgreementsListResponse GetAgreementsList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/AgreementService")] GetAgreementsListRequest GetAgreementsListRequest) {
            object[] results = this.Invoke("GetAgreementsList", new object[] {
                        GetAgreementsListRequest});
            return ((GetAgreementsListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAgreementsListAsync(GetAgreementsListRequest GetAgreementsListRequest) {
            this.GetAgreementsListAsync(GetAgreementsListRequest, null);
        }
        
        /// <remarks/>
        public void GetAgreementsListAsync(GetAgreementsListRequest GetAgreementsListRequest, object userState) {
            if ((this.GetAgreementsListOperationCompleted == null)) {
                this.GetAgreementsListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAgreementsListOperationCompleted);
            }
            this.InvokeAsync("GetAgreementsList", new object[] {
                        GetAgreementsListRequest}, this.GetAgreementsListOperationCompleted, userState);
        }
        
        private void OnGetAgreementsListOperationCompleted(object arg) {
            if ((this.GetAgreementsListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAgreementsListCompleted(this, new GetAgreementsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("AmendAgreementResponse", Namespace="http://uicds.org/AgreementService")]
        public AmendAgreementResponse AmendAgreement([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/AgreementService")] AmendAgreementRequest AmendAgreementRequest) {
            object[] results = this.Invoke("AmendAgreement", new object[] {
                        AmendAgreementRequest});
            return ((AmendAgreementResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AmendAgreementAsync(AmendAgreementRequest AmendAgreementRequest) {
            this.AmendAgreementAsync(AmendAgreementRequest, null);
        }
        
        /// <remarks/>
        public void AmendAgreementAsync(AmendAgreementRequest AmendAgreementRequest, object userState) {
            if ((this.AmendAgreementOperationCompleted == null)) {
                this.AmendAgreementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAmendAgreementOperationCompleted);
            }
            this.InvokeAsync("AmendAgreement", new object[] {
                        AmendAgreementRequest}, this.AmendAgreementOperationCompleted, userState);
        }
        
        private void OnAmendAgreementOperationCompleted(object arg) {
            if ((this.AmendAgreementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AmendAgreementCompleted(this, new AmendAgreementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetAgreementResponse", Namespace="http://uicds.org/AgreementService")]
        public GetAgreementResponse GetAgreement([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.org/AgreementService")] GetAgreementRequest GetAgreementRequest) {
            object[] results = this.Invoke("GetAgreement", new object[] {
                        GetAgreementRequest});
            return ((GetAgreementResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAgreementAsync(GetAgreementRequest GetAgreementRequest) {
            this.GetAgreementAsync(GetAgreementRequest, null);
        }
        
        /// <remarks/>
        public void GetAgreementAsync(GetAgreementRequest GetAgreementRequest, object userState) {
            if ((this.GetAgreementOperationCompleted == null)) {
                this.GetAgreementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAgreementOperationCompleted);
            }
            this.InvokeAsync("GetAgreement", new object[] {
                        GetAgreementRequest}, this.GetAgreementOperationCompleted, userState);
        }
        
        private void OnGetAgreementOperationCompleted(object arg) {
            if ((this.GetAgreementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAgreementCompleted(this, new GetAgreementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class CreateAgreementRequest {
        
        private string[] entityListField;
        
        private AgreementType agreementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entityID", IsNullable=false)]
        public string[] EntityList {
            get {
                return this.entityListField;
            }
            set {
                this.entityListField = value;
            }
        }
        
        /// <remarks/>
        public AgreementType Agreement {
            get {
                return this.agreementField;
            }
            set {
                this.agreementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/AgreementService")]
    public partial class AgreementType {
        
        private string agreementIDField;
        
        private string summaryField;
        
        private string[] partiesField;
        
        private AgreementTypeScope scopeField;
        
        private AgreementTypeContract contractField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string agreementID {
            get {
                return this.agreementIDField;
            }
            set {
                this.agreementIDField = value;
            }
        }
        
        /// <remarks/>
        public string summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entityID", IsNullable=false)]
        public string[] Parties {
            get {
                return this.partiesField;
            }
            set {
                this.partiesField = value;
            }
        }
        
        /// <remarks/>
        public AgreementTypeScope Scope {
            get {
                return this.scopeField;
            }
            set {
                this.scopeField = value;
            }
        }
        
        /// <remarks/>
        public AgreementTypeContract Contract {
            get {
                return this.contractField;
            }
            set {
                this.contractField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class AgreementTypeScope {
        
        private CoordinationActionType[] coordinationActionsField;
        
        private AgreementTypeScopePeriod periodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("action", IsNullable=false)]
        public CoordinationActionType[] coordinationActions {
            get {
                return this.coordinationActionsField;
            }
            set {
                this.coordinationActionsField = value;
            }
        }
        
        /// <remarks/>
        public AgreementTypeScopePeriod period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.org/AgreementService")]
    public partial class CoordinationActionType {
        
        private string incidentTypeField;
        
        private string actionTypeField;
        
        /// <remarks/>
        public string incidentType {
            get {
                return this.incidentTypeField;
            }
            set {
                this.incidentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string actionType {
            get {
                return this.actionTypeField;
            }
            set {
                this.actionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class AgreementTypeScopePeriod {
        
        private System.DateTime beginField;
        
        private System.DateTime endField;
        
        /// <remarks/>
        public System.DateTime begin {
            get {
                return this.beginField;
            }
            set {
                this.beginField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class AgreementTypeContract {
        
        private string contractRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string contractRef {
            get {
                return this.contractRefField;
            }
            set {
                this.contractRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class CreateAgreementResponse {
        
        private AgreementType agreementField;
        
        /// <remarks/>
        public AgreementType Agreement {
            get {
                return this.agreementField;
            }
            set {
                this.agreementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class RescindAgreementRequest {
        
        private string entityIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string entityID {
            get {
                return this.entityIDField;
            }
            set {
                this.entityIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class RescindAgreementResponse {
        
        private string entityIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string entityID {
            get {
                return this.entityIDField;
            }
            set {
                this.entityIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class GetAgreementsListRequest {
        
        private string entityIDField;
        
        private bool matchPartialsField;
        
        public GetAgreementsListRequest() {
            this.matchPartialsField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string entityID {
            get {
                return this.entityIDField;
            }
            set {
                this.entityIDField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool matchPartials {
            get {
                return this.matchPartialsField;
            }
            set {
                this.matchPartialsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class GetAgreementsListResponse {
        
        private string[] agreementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entityID", IsNullable=false)]
        public string[] Agreements {
            get {
                return this.agreementsField;
            }
            set {
                this.agreementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class AmendAgreementRequest {
        
        private string[] entityListField;
        
        private AgreementType agreementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entityID", IsNullable=false)]
        public string[] EntityList {
            get {
                return this.entityListField;
            }
            set {
                this.entityListField = value;
            }
        }
        
        /// <remarks/>
        public AgreementType Agreement {
            get {
                return this.agreementField;
            }
            set {
                this.agreementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class AmendAgreementResponse {
        
        private AgreementType agreementField;
        
        /// <remarks/>
        public AgreementType Agreement {
            get {
                return this.agreementField;
            }
            set {
                this.agreementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class GetAgreementRequest {
        
        private string entityIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string entityID {
            get {
                return this.entityIDField;
            }
            set {
                this.entityIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.org/AgreementService")]
    public partial class GetAgreementResponse {
        
        private AgreementType agreementField;
        
        /// <remarks/>
        public AgreementType Agreement {
            get {
                return this.agreementField;
            }
            set {
                this.agreementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void CreateAgreementCompletedEventHandler(object sender, CreateAgreementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateAgreementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateAgreementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateAgreementResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateAgreementResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void RescindAgreementCompletedEventHandler(object sender, RescindAgreementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RescindAgreementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RescindAgreementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RescindAgreementResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RescindAgreementResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetAgreementsListCompletedEventHandler(object sender, GetAgreementsListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAgreementsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAgreementsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAgreementsListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAgreementsListResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void AmendAgreementCompletedEventHandler(object sender, AmendAgreementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AmendAgreementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AmendAgreementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AmendAgreementResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AmendAgreementResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetAgreementCompletedEventHandler(object sender, GetAgreementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAgreementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAgreementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAgreementResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAgreementResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591