//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UICDS_Services.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:80/uicds/core/ws/services/IncidentManagementService")]
        public string UICDS_Services_IncidentManagementService_IncidentManagementServiceService {
            get {
                return ((string)(this["UICDS_Services_IncidentManagementService_IncidentManagementServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:80/uicds/core/ws/services/ResourceProfileService")]
        public string UICDS_Services_ResourceProfileService_ResourceProfileServiceService {
            get {
                return ((string)(this["UICDS_Services_ResourceProfileService_ResourceProfileServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:80/uicds/core/ws/services/ResourceInstanceService")]
        public string UICDS_Services_ResourceInstanceService_ResourceInstanceServiceService {
            get {
                return ((string)(this["UICDS_Services_ResourceInstanceService_ResourceInstanceServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:80/uicds/core/ws/services/DirectoryService")]
        public string UICDS_Services_DirectoryService_DirectoryServiceService {
            get {
                return ((string)(this["UICDS_Services_DirectoryService_DirectoryServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:80/uicds/core/ws/services/MapService")]
        public string UICDS_Services_MapService_MapServiceService {
            get {
                return ((string)(this["UICDS_Services_MapService_MapServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:80/uicds/core/ws/services/AgreementService")]
        public string UICDS_Services_AgreementService_AgreementServiceService {
            get {
                return ((string)(this["UICDS_Services_AgreementService_AgreementServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:80/uicds/core/ws/services/AlertService")]
        public string UICDS_Services_AlertService_AlertServiceService {
            get {
                return ((string)(this["UICDS_Services_AlertService_AlertServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:80/uicds/core/ws/services/BroadcastService")]
        public string UICDS_Services_BroadcastService_BroadcastServiceService {
            get {
                return ((string)(this["UICDS_Services_BroadcastService_BroadcastServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:80/uicds/core/ws/services/IAPService")]
        public string UICDS_Services_IAPService_IAPServiceService {
            get {
                return ((string)(this["UICDS_Services_IAPService_IAPServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:80/uicds/core/ws/services/IncidentCommandService")]
        public string UICDS_Services_IncidentCommandService_IncidentCommandServiceService {
            get {
                return ((string)(this["UICDS_Services_IncidentCommandService_IncidentCommandServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:80/uicds/core/ws/services/LEITSCService")]
        public string UICDS_Services_LEITSCService_LEITSCServiceService {
            get {
                return ((string)(this["UICDS_Services_LEITSCService_LEITSCServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:80/uicds/core/ws/services/LoggingService")]
        public string UICDS_Services_LoggingService_LoggingServiceService {
            get {
                return ((string)(this["UICDS_Services_LoggingService_LoggingServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:80/uicds/core/ws/services/NotificationService")]
        public string UICDS_Services_NotificationService_NotificationServiceService {
            get {
                return ((string)(this["UICDS_Services_NotificationService_NotificationServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:80/uicds/core/ws/services/SensorSerivce")]
        public string UICDS_Services_SensorService_SensorServiceService {
            get {
                return ((string)(this["UICDS_Services_SensorService_SensorServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:80/uicds/core/ws/Services/TaskingService")]
        public string UICDS_Services_TaskingService_TaskingServiceService {
            get {
                return ((string)(this["UICDS_Services_TaskingService_TaskingServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:80/uicds/core/ws/services/WorkProductService")]
        public string UICDS_Services_WorkProductService_WorkProductServiceService {
            get {
                return ((string)(this["UICDS_Services_WorkProductService_WorkProductServiceService"]));
            }
        }
    }
}
