//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3082.
// 
#pragma warning disable 1591

namespace TestJavaWS.AlertWS2 {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AlertServiceSoap11", Namespace="http://uicds.dctd.saic.com/schemas/AlertService")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComplexObjectType))]
    public partial class AlertServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAlertOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelAlertOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListOfAlertsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateAlertOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAlertByAlertIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AlertServiceService() {
            this.Url = global::TestJavaWS.Properties.Settings.Default.TestJavaWS_AlertWS2_AlertServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAlertCompletedEventHandler GetAlertCompleted;
        
        /// <remarks/>
        public event CancelAlertCompletedEventHandler CancelAlertCompleted;
        
        /// <remarks/>
        public event GetListOfAlertsCompletedEventHandler GetListOfAlertsCompleted;
        
        /// <remarks/>
        public event CreateAlertCompletedEventHandler CreateAlertCompleted;
        
        /// <remarks/>
        public event GetAlertByAlertIdCompletedEventHandler GetAlertByAlertIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetAlertResponse", Namespace="http://uicds.dctd.saic.com/schemas/AlertService")]
        public GetAlertResponse GetAlert([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.dctd.saic.com/schemas/AlertService")] string GetAlertRequest) {
            object[] results = this.Invoke("GetAlert", new object[] {
                        GetAlertRequest});
            return ((GetAlertResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAlertAsync(string GetAlertRequest) {
            this.GetAlertAsync(GetAlertRequest, null);
        }
        
        /// <remarks/>
        public void GetAlertAsync(string GetAlertRequest, object userState) {
            if ((this.GetAlertOperationCompleted == null)) {
                this.GetAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAlertOperationCompleted);
            }
            this.InvokeAsync("GetAlert", new object[] {
                        GetAlertRequest}, this.GetAlertOperationCompleted, userState);
        }
        
        private void OnGetAlertOperationCompleted(object arg) {
            if ((this.GetAlertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAlertCompleted(this, new GetAlertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CancelAlertResponse", Namespace="http://uicds.dctd.saic.com/schemas/AlertService")]
        public CancelAlertResponse CancelAlert([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.dctd.saic.com/schemas/AlertService")] string CancelAlertRequest) {
            object[] results = this.Invoke("CancelAlert", new object[] {
                        CancelAlertRequest});
            return ((CancelAlertResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CancelAlertAsync(string CancelAlertRequest) {
            this.CancelAlertAsync(CancelAlertRequest, null);
        }
        
        /// <remarks/>
        public void CancelAlertAsync(string CancelAlertRequest, object userState) {
            if ((this.CancelAlertOperationCompleted == null)) {
                this.CancelAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelAlertOperationCompleted);
            }
            this.InvokeAsync("CancelAlert", new object[] {
                        CancelAlertRequest}, this.CancelAlertOperationCompleted, userState);
        }
        
        private void OnCancelAlertOperationCompleted(object arg) {
            if ((this.CancelAlertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelAlertCompleted(this, new CancelAlertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetListOfAlertsResponse", Namespace="http://uicds.dctd.saic.com/schemas/AlertService")]
        public GetListOfAlertsResponse GetListOfAlerts([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.dctd.saic.com/schemas/AlertService")] string GetListOfAlertsRequest) {
            object[] results = this.Invoke("GetListOfAlerts", new object[] {
                        GetListOfAlertsRequest});
            return ((GetListOfAlertsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetListOfAlertsAsync(string GetListOfAlertsRequest) {
            this.GetListOfAlertsAsync(GetListOfAlertsRequest, null);
        }
        
        /// <remarks/>
        public void GetListOfAlertsAsync(string GetListOfAlertsRequest, object userState) {
            if ((this.GetListOfAlertsOperationCompleted == null)) {
                this.GetListOfAlertsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListOfAlertsOperationCompleted);
            }
            this.InvokeAsync("GetListOfAlerts", new object[] {
                        GetListOfAlertsRequest}, this.GetListOfAlertsOperationCompleted, userState);
        }
        
        private void OnGetListOfAlertsOperationCompleted(object arg) {
            if ((this.GetListOfAlertsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListOfAlertsCompleted(this, new GetListOfAlertsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CreateAlertResponse", Namespace="http://uicds.dctd.saic.com/schemas/AlertService")]
        public CreateAlertResponse CreateAlert([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.dctd.saic.com/schemas/AlertService")] UICDSAlertAdapterType CreateAlertRequest) {
            object[] results = this.Invoke("CreateAlert", new object[] {
                        CreateAlertRequest});
            return ((CreateAlertResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAlertAsync(UICDSAlertAdapterType CreateAlertRequest) {
            this.CreateAlertAsync(CreateAlertRequest, null);
        }
        
        /// <remarks/>
        public void CreateAlertAsync(UICDSAlertAdapterType CreateAlertRequest, object userState) {
            if ((this.CreateAlertOperationCompleted == null)) {
                this.CreateAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateAlertOperationCompleted);
            }
            this.InvokeAsync("CreateAlert", new object[] {
                        CreateAlertRequest}, this.CreateAlertOperationCompleted, userState);
        }
        
        private void OnCreateAlertOperationCompleted(object arg) {
            if ((this.CreateAlertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateAlertCompleted(this, new CreateAlertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetAlertByAlertIdResponse", Namespace="http://uicds.dctd.saic.com/schemas/AlertService")]
        public GetAlertByAlertIdResponse GetAlertByAlertId([System.Xml.Serialization.XmlElementAttribute(Namespace="http://uicds.dctd.saic.com/schemas/AlertService")] string GetAlertByAlertIdRequest) {
            object[] results = this.Invoke("GetAlertByAlertId", new object[] {
                        GetAlertByAlertIdRequest});
            return ((GetAlertByAlertIdResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAlertByAlertIdAsync(string GetAlertByAlertIdRequest) {
            this.GetAlertByAlertIdAsync(GetAlertByAlertIdRequest, null);
        }
        
        /// <remarks/>
        public void GetAlertByAlertIdAsync(string GetAlertByAlertIdRequest, object userState) {
            if ((this.GetAlertByAlertIdOperationCompleted == null)) {
                this.GetAlertByAlertIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAlertByAlertIdOperationCompleted);
            }
            this.InvokeAsync("GetAlertByAlertId", new object[] {
                        GetAlertByAlertIdRequest}, this.GetAlertByAlertIdOperationCompleted, userState);
        }
        
        private void OnGetAlertByAlertIdOperationCompleted(object arg) {
            if ((this.GetAlertByAlertIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAlertByAlertIdCompleted(this, new GetAlertByAlertIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.dctd.saic.com/schemas/AlertService")]
    public partial class GetAlertResponse {
        
        private EDXLDistribution eDXLDistributionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:tc:emergency:EDXL:DE:1.0")]
        public EDXLDistribution EDXLDistribution {
            get {
                return this.eDXLDistributionField;
            }
            set {
                this.eDXLDistributionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:emergency:EDXL:DE:1.0")]
    public partial class EDXLDistribution {
        
        private string distributionIDField;
        
        private string senderIDField;
        
        private System.DateTime dateTimeSentField;
        
        private statusValues distributionStatusField;
        
        private typeValues distributionTypeField;
        
        private string combinedConfidentialityField;
        
        private string languageField;
        
        private valueListType[] senderRoleField;
        
        private valueListType[] recipientRoleField;
        
        private valueListType[] keywordField;
        
        private string[] distributionReferenceField;
        
        private valueSchemeType[] explicitAddressField;
        
        private targetAreaType[] targetAreaField;
        
        private contentObjectType[] contentObjectField;
        
        /// <remarks/>
        public string distributionID {
            get {
                return this.distributionIDField;
            }
            set {
                this.distributionIDField = value;
            }
        }
        
        /// <remarks/>
        public string senderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dateTimeSent {
            get {
                return this.dateTimeSentField;
            }
            set {
                this.dateTimeSentField = value;
            }
        }
        
        /// <remarks/>
        public statusValues distributionStatus {
            get {
                return this.distributionStatusField;
            }
            set {
                this.distributionStatusField = value;
            }
        }
        
        /// <remarks/>
        public typeValues distributionType {
            get {
                return this.distributionTypeField;
            }
            set {
                this.distributionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string combinedConfidentiality {
            get {
                return this.combinedConfidentialityField;
            }
            set {
                this.combinedConfidentialityField = value;
            }
        }
        
        /// <remarks/>
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("senderRole")]
        public valueListType[] senderRole {
            get {
                return this.senderRoleField;
            }
            set {
                this.senderRoleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recipientRole")]
        public valueListType[] recipientRole {
            get {
                return this.recipientRoleField;
            }
            set {
                this.recipientRoleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keyword")]
        public valueListType[] keyword {
            get {
                return this.keywordField;
            }
            set {
                this.keywordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("distributionReference")]
        public string[] distributionReference {
            get {
                return this.distributionReferenceField;
            }
            set {
                this.distributionReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("explicitAddress")]
        public valueSchemeType[] explicitAddress {
            get {
                return this.explicitAddressField;
            }
            set {
                this.explicitAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("targetArea")]
        public targetAreaType[] targetArea {
            get {
                return this.targetAreaField;
            }
            set {
                this.targetAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contentObject")]
        public contentObjectType[] contentObject {
            get {
                return this.contentObjectField;
            }
            set {
                this.contentObjectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:emergency:EDXL:DE:1.0")]
    public enum statusValues {
        
        /// <remarks/>
        Actual,
        
        /// <remarks/>
        Exercise,
        
        /// <remarks/>
        System,
        
        /// <remarks/>
        Test,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:emergency:EDXL:DE:1.0")]
    public enum typeValues {
        
        /// <remarks/>
        Report,
        
        /// <remarks/>
        Update,
        
        /// <remarks/>
        Cancel,
        
        /// <remarks/>
        Request,
        
        /// <remarks/>
        Response,
        
        /// <remarks/>
        Dispatch,
        
        /// <remarks/>
        Ack,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        SensorConfiguration,
        
        /// <remarks/>
        SensorControl,
        
        /// <remarks/>
        SensorStatus,
        
        /// <remarks/>
        SensorDetection,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:emergency:EDXL:DE:1.0")]
    public partial class valueListType {
        
        private string valueListUrnField;
        
        private string[] valueField;
        
        /// <remarks/>
        public string valueListUrn {
            get {
                return this.valueListUrnField;
            }
            set {
                this.valueListUrnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public string[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UICDSAlertAdapterType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/structures/2.0")]
    public abstract partial class ComplexObjectType {
        
        private string idField;
        
        private string metadataField;
        
        private string linkMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="IDREFS")]
        public string metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="IDREFS")]
        public string linkMetadata {
            get {
                return this.linkMetadataField;
            }
            set {
                this.linkMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uicds.dctd.saic.com/schemas/AlertService")]
    public partial class UICDSAlertAdapterType : ComplexObjectType {
        
        private alert alertField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:tc:emergency:cap:1.1")]
        public alert alert {
            get {
                return this.alertField;
            }
            set {
                this.alertField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:emergency:cap:1.1")]
    public partial class alert {
        
        private string identifierField;
        
        private string senderField;
        
        private System.DateTime sentField;
        
        private alertStatus statusField;
        
        private alertMsgType msgTypeField;
        
        private string sourceField;
        
        private alertScope scopeField;
        
        private string restrictionField;
        
        private string addressesField;
        
        private string[] codeField;
        
        private string noteField;
        
        private string referencesField;
        
        private string incidentsField;
        
        private alertInfo[] infoField;
        
        /// <remarks/>
        public string identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public string sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime sent {
            get {
                return this.sentField;
            }
            set {
                this.sentField = value;
            }
        }
        
        /// <remarks/>
        public alertStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public alertMsgType msgType {
            get {
                return this.msgTypeField;
            }
            set {
                this.msgTypeField = value;
            }
        }
        
        /// <remarks/>
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public alertScope scope {
            get {
                return this.scopeField;
            }
            set {
                this.scopeField = value;
            }
        }
        
        /// <remarks/>
        public string restriction {
            get {
                return this.restrictionField;
            }
            set {
                this.restrictionField = value;
            }
        }
        
        /// <remarks/>
        public string addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("code")]
        public string[] code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        public string references {
            get {
                return this.referencesField;
            }
            set {
                this.referencesField = value;
            }
        }
        
        /// <remarks/>
        public string incidents {
            get {
                return this.incidentsField;
            }
            set {
                this.incidentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("info")]
        public alertInfo[] info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:emergency:cap:1.1")]
    public enum alertStatus {
        
        /// <remarks/>
        Actual,
        
        /// <remarks/>
        Exercise,
        
        /// <remarks/>
        System,
        
        /// <remarks/>
        Test,
        
        /// <remarks/>
        Draft,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:emergency:cap:1.1")]
    public enum alertMsgType {
        
        /// <remarks/>
        Alert,
        
        /// <remarks/>
        Update,
        
        /// <remarks/>
        Cancel,
        
        /// <remarks/>
        Ack,
        
        /// <remarks/>
        Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:emergency:cap:1.1")]
    public enum alertScope {
        
        /// <remarks/>
        Public,
        
        /// <remarks/>
        Restricted,
        
        /// <remarks/>
        Private,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:emergency:cap:1.1")]
    public partial class alertInfo {
        
        private string languageField;
        
        private alertInfoCategory[] categoryField;
        
        private string eventField;
        
        private alertInfoResponseType[] responseTypeField;
        
        private alertInfoUrgency urgencyField;
        
        private alertInfoSeverity severityField;
        
        private alertInfoCertainty certaintyField;
        
        private string audienceField;
        
        private alertInfoEventCode[] eventCodeField;
        
        private System.DateTime effectiveField;
        
        private bool effectiveFieldSpecified;
        
        private System.DateTime onsetField;
        
        private bool onsetFieldSpecified;
        
        private System.DateTime expiresField;
        
        private bool expiresFieldSpecified;
        
        private string senderNameField;
        
        private string headlineField;
        
        private string descriptionField;
        
        private string instructionField;
        
        private string webField;
        
        private string contactField;
        
        private alertInfoParameter[] parameterField;
        
        private alertInfoResource[] resourceField;
        
        private alertInfoArea[] areaField;
        
        public alertInfo() {
            this.languageField = "en-US";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="language")]
        [System.ComponentModel.DefaultValueAttribute("en-US")]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("category")]
        public alertInfoCategory[] category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string @event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("responseType")]
        public alertInfoResponseType[] responseType {
            get {
                return this.responseTypeField;
            }
            set {
                this.responseTypeField = value;
            }
        }
        
        /// <remarks/>
        public alertInfoUrgency urgency {
            get {
                return this.urgencyField;
            }
            set {
                this.urgencyField = value;
            }
        }
        
        /// <remarks/>
        public alertInfoSeverity severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        public alertInfoCertainty certainty {
            get {
                return this.certaintyField;
            }
            set {
                this.certaintyField = value;
            }
        }
        
        /// <remarks/>
        public string audience {
            get {
                return this.audienceField;
            }
            set {
                this.audienceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eventCode")]
        public alertInfoEventCode[] eventCode {
            get {
                return this.eventCodeField;
            }
            set {
                this.eventCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime effective {
            get {
                return this.effectiveField;
            }
            set {
                this.effectiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool effectiveSpecified {
            get {
                return this.effectiveFieldSpecified;
            }
            set {
                this.effectiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime onset {
            get {
                return this.onsetField;
            }
            set {
                this.onsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool onsetSpecified {
            get {
                return this.onsetFieldSpecified;
            }
            set {
                this.onsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime expires {
            get {
                return this.expiresField;
            }
            set {
                this.expiresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expiresSpecified {
            get {
                return this.expiresFieldSpecified;
            }
            set {
                this.expiresFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string senderName {
            get {
                return this.senderNameField;
            }
            set {
                this.senderNameField = value;
            }
        }
        
        /// <remarks/>
        public string headline {
            get {
                return this.headlineField;
            }
            set {
                this.headlineField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string instruction {
            get {
                return this.instructionField;
            }
            set {
                this.instructionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string web {
            get {
                return this.webField;
            }
            set {
                this.webField = value;
            }
        }
        
        /// <remarks/>
        public string contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter")]
        public alertInfoParameter[] parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resource")]
        public alertInfoResource[] resource {
            get {
                return this.resourceField;
            }
            set {
                this.resourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("area")]
        public alertInfoArea[] area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:emergency:cap:1.1")]
    public enum alertInfoCategory {
        
        /// <remarks/>
        Geo,
        
        /// <remarks/>
        Met,
        
        /// <remarks/>
        Safety,
        
        /// <remarks/>
        Security,
        
        /// <remarks/>
        Rescue,
        
        /// <remarks/>
        Fire,
        
        /// <remarks/>
        Health,
        
        /// <remarks/>
        Env,
        
        /// <remarks/>
        Transport,
        
        /// <remarks/>
        Infra,
        
        /// <remarks/>
        CBRNE,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:emergency:cap:1.1")]
    public enum alertInfoResponseType {
        
        /// <remarks/>
        Shelter,
        
        /// <remarks/>
        Evacuate,
        
        /// <remarks/>
        Prepare,
        
        /// <remarks/>
        Execute,
        
        /// <remarks/>
        Monitor,
        
        /// <remarks/>
        Assess,
        
        /// <remarks/>
        None,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:emergency:cap:1.1")]
    public enum alertInfoUrgency {
        
        /// <remarks/>
        Immediate,
        
        /// <remarks/>
        Expected,
        
        /// <remarks/>
        Future,
        
        /// <remarks/>
        Past,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:emergency:cap:1.1")]
    public enum alertInfoSeverity {
        
        /// <remarks/>
        Extreme,
        
        /// <remarks/>
        Severe,
        
        /// <remarks/>
        Moderate,
        
        /// <remarks/>
        Minor,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:emergency:cap:1.1")]
    public enum alertInfoCertainty {
        
        /// <remarks/>
        Observed,
        
        /// <remarks/>
        Likely,
        
        /// <remarks/>
        Possible,
        
        /// <remarks/>
        Unlikely,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:emergency:cap:1.1")]
    public partial class alertInfoEventCode {
        
        private string valueNameField;
        
        private string valueField;
        
        /// <remarks/>
        public string valueName {
            get {
                return this.valueNameField;
            }
            set {
                this.valueNameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:emergency:cap:1.1")]
    public partial class alertInfoParameter {
        
        private string valueNameField;
        
        private string valueField;
        
        /// <remarks/>
        public string valueName {
            get {
                return this.valueNameField;
            }
            set {
                this.valueNameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:emergency:cap:1.1")]
    public partial class alertInfoResource {
        
        private string resourceDescField;
        
        private string mimeTypeField;
        
        private string sizeField;
        
        private string uriField;
        
        private string derefUriField;
        
        private string digestField;
        
        /// <remarks/>
        public string resourceDesc {
            get {
                return this.resourceDescField;
            }
            set {
                this.resourceDescField = value;
            }
        }
        
        /// <remarks/>
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
        
        /// <remarks/>
        public string derefUri {
            get {
                return this.derefUriField;
            }
            set {
                this.derefUriField = value;
            }
        }
        
        /// <remarks/>
        public string digest {
            get {
                return this.digestField;
            }
            set {
                this.digestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:emergency:cap:1.1")]
    public partial class alertInfoArea {
        
        private string areaDescField;
        
        private string[] polygonField;
        
        private string[] circleField;
        
        private alertInfoAreaGeocode[] geocodeField;
        
        private string altitudeField;
        
        private string ceilingField;
        
        /// <remarks/>
        public string areaDesc {
            get {
                return this.areaDescField;
            }
            set {
                this.areaDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("polygon")]
        public string[] polygon {
            get {
                return this.polygonField;
            }
            set {
                this.polygonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("circle")]
        public string[] circle {
            get {
                return this.circleField;
            }
            set {
                this.circleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("geocode")]
        public alertInfoAreaGeocode[] geocode {
            get {
                return this.geocodeField;
            }
            set {
                this.geocodeField = value;
            }
        }
        
        /// <remarks/>
        public string altitude {
            get {
                return this.altitudeField;
            }
            set {
                this.altitudeField = value;
            }
        }
        
        /// <remarks/>
        public string ceiling {
            get {
                return this.ceilingField;
            }
            set {
                this.ceilingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:emergency:cap:1.1")]
    public partial class alertInfoAreaGeocode {
        
        private string valueNameField;
        
        private string valueField;
        
        /// <remarks/>
        public string valueName {
            get {
                return this.valueNameField;
            }
            set {
                this.valueNameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:emergency:EDXL:DE:1.0")]
    public partial class anyXMLType {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:emergency:EDXL:DE:1.0")]
    public partial class xmlContentType {
        
        private anyXMLType[] keyXMLContentField;
        
        private anyXMLType[] embeddedXMLContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keyXMLContent")]
        public anyXMLType[] keyXMLContent {
            get {
                return this.keyXMLContentField;
            }
            set {
                this.keyXMLContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("embeddedXMLContent")]
        public anyXMLType[] embeddedXMLContent {
            get {
                return this.embeddedXMLContentField;
            }
            set {
                this.embeddedXMLContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:emergency:EDXL:DE:1.0")]
    public partial class nonXMLContentType {
        
        private string mimeTypeField;
        
        private string sizeField;
        
        private string digestField;
        
        private string uriField;
        
        private byte[] contentDataField;
        
        /// <remarks/>
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        public string digest {
            get {
                return this.digestField;
            }
            set {
                this.digestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] contentData {
            get {
                return this.contentDataField;
            }
            set {
                this.contentDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:emergency:EDXL:DE:1.0")]
    public partial class contentObjectType {
        
        private string contentDescriptionField;
        
        private valueListType[] contentKeywordField;
        
        private string incidentIDField;
        
        private string incidentDescriptionField;
        
        private valueListType[] originatorRoleField;
        
        private valueListType[] consumerRoleField;
        
        private string confidentialityField;
        
        private object itemField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public string contentDescription {
            get {
                return this.contentDescriptionField;
            }
            set {
                this.contentDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contentKeyword")]
        public valueListType[] contentKeyword {
            get {
                return this.contentKeywordField;
            }
            set {
                this.contentKeywordField = value;
            }
        }
        
        /// <remarks/>
        public string incidentID {
            get {
                return this.incidentIDField;
            }
            set {
                this.incidentIDField = value;
            }
        }
        
        /// <remarks/>
        public string incidentDescription {
            get {
                return this.incidentDescriptionField;
            }
            set {
                this.incidentDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("originatorRole")]
        public valueListType[] originatorRole {
            get {
                return this.originatorRoleField;
            }
            set {
                this.originatorRoleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("consumerRole")]
        public valueListType[] consumerRole {
            get {
                return this.consumerRoleField;
            }
            set {
                this.consumerRoleField = value;
            }
        }
        
        /// <remarks/>
        public string confidentiality {
            get {
                return this.confidentialityField;
            }
            set {
                this.confidentialityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nonXMLContent", typeof(nonXMLContentType))]
        [System.Xml.Serialization.XmlElementAttribute("xmlContent", typeof(xmlContentType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:emergency:EDXL:DE:1.0")]
    public partial class targetAreaType {
        
        private string[] circleField;
        
        private string[] polygonField;
        
        private string[] countryField;
        
        private string[] subdivisionField;
        
        private string[] locCodeUNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("circle")]
        public string[] circle {
            get {
                return this.circleField;
            }
            set {
                this.circleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("polygon")]
        public string[] polygon {
            get {
                return this.polygonField;
            }
            set {
                this.polygonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("country")]
        public string[] country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subdivision")]
        public string[] subdivision {
            get {
                return this.subdivisionField;
            }
            set {
                this.subdivisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("locCodeUN")]
        public string[] locCodeUN {
            get {
                return this.locCodeUNField;
            }
            set {
                this.locCodeUNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:emergency:EDXL:DE:1.0")]
    public partial class valueSchemeType {
        
        private string explicitAddressSchemeField;
        
        private string[] explicitAddressValueField;
        
        /// <remarks/>
        public string explicitAddressScheme {
            get {
                return this.explicitAddressSchemeField;
            }
            set {
                this.explicitAddressSchemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("explicitAddressValue")]
        public string[] explicitAddressValue {
            get {
                return this.explicitAddressValueField;
            }
            set {
                this.explicitAddressValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.dctd.saic.com/schemas/AlertService")]
    public partial class CancelAlertResponse {
        
        private EDXLDistribution eDXLDistributionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:tc:emergency:EDXL:DE:1.0")]
        public EDXLDistribution EDXLDistribution {
            get {
                return this.eDXLDistributionField;
            }
            set {
                this.eDXLDistributionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.dctd.saic.com/schemas/AlertService")]
    public partial class GetListOfAlertsResponse {
        
        private EDXLDistribution eDXLDistributionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:tc:emergency:EDXL:DE:1.0")]
        public EDXLDistribution EDXLDistribution {
            get {
                return this.eDXLDistributionField;
            }
            set {
                this.eDXLDistributionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.dctd.saic.com/schemas/AlertService")]
    public partial class CreateAlertResponse {
        
        private EDXLDistribution eDXLDistributionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:tc:emergency:EDXL:DE:1.0")]
        public EDXLDistribution EDXLDistribution {
            get {
                return this.eDXLDistributionField;
            }
            set {
                this.eDXLDistributionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://uicds.dctd.saic.com/schemas/AlertService")]
    public partial class GetAlertByAlertIdResponse {
        
        private EDXLDistribution eDXLDistributionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:tc:emergency:EDXL:DE:1.0")]
        public EDXLDistribution EDXLDistribution {
            get {
                return this.eDXLDistributionField;
            }
            set {
                this.eDXLDistributionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetAlertCompletedEventHandler(object sender, GetAlertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAlertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAlertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAlertResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAlertResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void CancelAlertCompletedEventHandler(object sender, CancelAlertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelAlertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelAlertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CancelAlertResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CancelAlertResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetListOfAlertsCompletedEventHandler(object sender, GetListOfAlertsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListOfAlertsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListOfAlertsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetListOfAlertsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetListOfAlertsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void CreateAlertCompletedEventHandler(object sender, CreateAlertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateAlertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateAlertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateAlertResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateAlertResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetAlertByAlertIdCompletedEventHandler(object sender, GetAlertByAlertIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAlertByAlertIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAlertByAlertIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAlertByAlertIdResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAlertByAlertIdResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591